/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border) / <alpha-value>)',
        input: 'hsl(var(--input) / <alpha-value>)',
        ring: 'hsl(var(--ring) / <alpha-value>)',
        background: 'hsl(var(--background) / <alpha-value>)',
        foreground: 'hsl(var(--foreground) / <alpha-value>)',
        primary: {
          DEFAULT: 'hsl(var(--primary) / <alpha-value>)',
          foreground: 'hsl(var(--primary-foreground) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary) / <alpha-value>)',
          foreground: 'hsl(var(--secondary-foreground) / <alpha-value>)',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive) / <alpha-value>)',
          foreground: 'hsl(var(--destructive-foreground) / <alpha-value>)',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted) / <alpha-value>)',
          foreground: 'hsl(var(--muted-foreground) / <alpha-value>)',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent) / <alpha-value>)',
          foreground: 'hsl(var(--accent-foreground) / <alpha-value>)',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover) / <alpha-value>)',
          foreground: 'hsl(var(--popover-foreground) / <alpha-value>)',
        },
        card: {
          DEFAULT: 'hsl(var(--card) / <alpha-value>)',
          foreground: 'hsl(var(--card-foreground) / <alpha-value>)',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar) / <alpha-value>)',
          foreground: 'hsl(var(--sidebar-foreground) / <alpha-value>)',
          primary: 'hsl(var(--sidebar-primary) / <alpha-value>)',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground) / <alpha-value>)',
          accent: 'hsl(var(--sidebar-accent) / <alpha-value>)',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground) / <alpha-value>)',
          border: 'hsl(var(--sidebar-border) / <alpha-value>)',
          ring: 'hsl(var(--sidebar-ring) / <alpha-value>)',
        },
        'bg-deepest': 'hsl(var(--bg-deepest) / <alpha-value>)',
        'bg-deep': 'hsl(var(--bg-deep) / <alpha-value>)',
        'bg-black': 'hsl(var(--bg-black) / <alpha-value>)',
        'bg-warm-black': 'hsl(var(--bg-warm-black) / <alpha-value>)',
        panel: 'hsl(var(--bg-panel) / <alpha-value>)',
        vellum: 'hsl(var(--vellum) / <alpha-value>)',
        gold: {
          DEFAULT: 'hsl(var(--gold) / <alpha-value>)',
          deep: 'hsl(var(--gold-deep) / <alpha-value>)',
          bright: 'hsl(var(--gold-bright) / <alpha-value>)',
          soft: 'hsl(var(--gold-soft) / <alpha-value>)',
          ember: 'hsl(var(--gold-ember) / <alpha-value>)',
          line: 'hsl(var(--gold-line) / <alpha-value>)',
        },
        'gold-bright': 'hsl(var(--gold-bright) / <alpha-value>)',
        'gold-deep': 'hsl(var(--gold-deep) / <alpha-value>)',
        'gold-ember': 'hsl(var(--gold-ember) / <alpha-value>)',
        'gold-line': 'hsl(var(--gold-line) / <alpha-value>)',
        ember: 'hsl(var(--ember-red) / <alpha-value>)',
        'ember-glow': 'hsl(var(--ember-glow) / <alpha-value>)',
        ink: {
          DEFAULT: 'hsl(var(--ink-black) / <alpha-value>)',
          black: 'hsl(var(--ink-black) / <alpha-value>)',
          deep: 'hsl(var(--ink-deep) / <alpha-value>)',
        },
        parchment: 'hsl(var(--parchment) / <alpha-value>)',
        fog: 'hsl(var(--fog-warm) / <alpha-value>)',
        historical: 'hsl(var(--historical-gold) / <alpha-value>)',
        stone: {
          850: 'hsl(var(--stone-850) / <alpha-value>)',
          950: 'hsl(var(--stone-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', '"Playfair Display"', 'serif'],
        body: ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      boxShadow: {
        'gold-bloom': '0 0 60px hsl(var(--gold-bright) / 0.22)',
        'card-lux': 'inset 0 0 0 1px hsl(var(--gold) / 0.08), inset 0 0 40px hsl(var(--gold) / 0.08), 0 20px 60px hsl(var(--shadow-black) / 0.6)',
      },
      opacity: {
        8: '0.08',
        12: '0.12',
        18: '0.18',
        22: '0.22',
        24: '0.24',
        28: '0.28',
        32: '0.32',
        34: '0.34',
        35: '0.35',
        38: '0.38',
        42: '0.42',
        45: '0.45',
        55: '0.55',
        58: '0.58',
        65: '0.65',
        72: '0.72',
        78: '0.78',
      },
    },
  },
  plugins: [],
}
