const mongoose = require('mongoose');
const dotenv = require('dotenv');
const bcrypt = require('bcryptjs');
dotenv.config();

const City = require('./models/City');
const Place = require('./models/Place');
const User = require('./models/User');

const cities = [
  { name: 'İstanbul', nameEn: 'Istanbul', region: 'Marmara', location: { type: 'Point', coordinates: [28.9784, 41.0082] }, description: 'Tarihin kalbi, iki kıtanın buluşma noktası', placeCount: 0 },
  { name: 'Ankara', nameEn: 'Ankara', region: 'İç Anadolu', location: { type: 'Point', coordinates: [32.8597, 39.9334] }, description: 'Cumhuriyetin başkenti', placeCount: 0 },
  { name: 'İzmir', nameEn: 'Izmir', region: 'Ege', location: { type: 'Point', coordinates: [27.1428, 38.4237] }, description: 'Ege\'nin incisi', placeCount: 0 },
  { name: 'Konya', nameEn: 'Konya', region: 'İç Anadolu', location: { type: 'Point', coordinates: [32.4872, 37.8746] }, description: 'Mevlana\'nın şehri', placeCount: 0 },
  { name: 'Kayseri', nameEn: 'Kayseri', region: 'Ic Anadolu', location: { type: 'Point', coordinates: [35.4787, 38.7205] }, description: 'Selcuklu ve Osmanli mirasiyla Erciyes eteklerinde tarihi merkez', placeCount: 0 },
  { name: 'Eskisehir', nameEn: 'Eskisehir', region: 'Ic Anadolu', location: { type: 'Point', coordinates: [30.5256, 39.7767] }, description: 'Odunpazari evleri ve modern kultur yasamiyla one cikan Ic Anadolu sehri', placeCount: 0 },
  { name: 'Sivas', nameEn: 'Sivas', region: 'Ic Anadolu', location: { type: 'Point', coordinates: [37.0161, 39.7477] }, description: 'Selcuklu eserleri ve Divrigi mirasiyla taninan tarihi kent', placeCount: 0 },
  { name: 'Bursa', nameEn: 'Bursa', region: 'Marmara', location: { type: 'Point', coordinates: [29.0601, 40.1826] }, description: 'Osmanlı\'nın ilk başkenti', placeCount: 0 },
  { name: 'Edirne', nameEn: 'Edirne', region: 'Marmara', location: { type: 'Point', coordinates: [26.5557, 41.6771] }, description: 'Osmanli mimarisinin basyapitlarina ev sahipligi yapan serhat sehri', placeCount: 0 },
  { name: 'Canakkale', nameEn: 'Canakkale', region: 'Marmara', location: { type: 'Point', coordinates: [26.4086, 40.1467] }, description: 'Troyadan Geliboluya uzanan tarih koridoru', placeCount: 0 },
  { name: 'Trabzon', nameEn: 'Trabzon', region: 'Karadeniz', location: { type: 'Point', coordinates: [39.7178, 41.0027] }, description: 'Karadeniz\'in gözbebeği', placeCount: 0 },
  { name: 'Samsun', nameEn: 'Samsun', region: 'Karadeniz', location: { type: 'Point', coordinates: [36.3361, 41.2867] }, description: 'Kurtuluş Savaşı\'nın başladığı şehir', placeCount: 0 },
  { name: 'Sinop', nameEn: 'Sinop', region: 'Karadeniz', location: { type: 'Point', coordinates: [35.1582, 42.0231] }, description: 'Karadeniz\'in en uç noktası', placeCount: 0 },
  { name: 'Antalya', nameEn: 'Antalya', region: 'Akdeniz', location: { type: 'Point', coordinates: [30.7133, 36.8969] }, description: 'Turquoise Coast\'un kalbi', placeCount: 0 },
  { name: 'Cappadocia', nameEn: 'Cappadocia', region: 'İç Anadolu', location: { type: 'Point', coordinates: [34.8457, 38.6431] }, description: 'Peri bacaları ve yeraltı şehirleri', placeCount: 0 },
  { name: 'Muğla', nameEn: 'Mugla', region: 'Ege', location: { type: 'Point', coordinates: [28.3665, 37.2153] }, description: 'Ege\'nin ve Akdeniz\'in buluştuğu yer', placeCount: 0 },
  { name: 'Aydın', nameEn: 'Aydin', region: 'Ege', location: { type: 'Point', coordinates: [27.8456, 37.8380] }, description: 'Antik kentler diyarı', placeCount: 0 },
  { name: 'Denizli', nameEn: 'Denizli', region: 'Ege', location: { type: 'Point', coordinates: [29.0875, 37.7830] }, description: 'Pamukkale travertenlerinin ev sahibi', placeCount: 0 },
  { name: 'Erzurum', nameEn: 'Erzurum', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [41.2769, 39.9043] }, description: 'Selçuklu, İlhanlı ve Osmanlı mirasının güçlü izlerini taşıyan yüksek plato şehri', placeCount: 0 },
  { name: 'Kars', nameEn: 'Kars', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [43.0975, 40.6013] }, description: 'Ani ören yeri, taş mimarisi ve sınır kültürüyle Doğu Anadolu\'nun tarih kapısı', placeCount: 0 },
  { name: 'Van', nameEn: 'Van', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [43.3800, 38.5012] }, description: 'Urartu mirası, Van Gölü ve çok katmanlı kültürel dokusuyla öne çıkan şehir', placeCount: 0 },
  { name: 'Ağrı', nameEn: 'Agri', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [43.0503, 39.7191] }, description: 'İshak Paşa Sarayı ve Ağrı Dağı çevresindeki tarihî peyzajıyla bilinen sınır kenti', placeCount: 0 },
  { name: 'Iğdır', nameEn: 'Igdir', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [44.0450, 39.9237] }, description: 'Aras Vadisi boyunca uzanan kültürel geçiş yolları ve tarihî kalıntılarıyla tanınır', placeCount: 0 },
  { name: 'Ardahan', nameEn: 'Ardahan', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [42.7022, 41.1105] }, description: 'Kura Nehri çevresinde kaleleri ve yayla kültürüyle öne çıkan serhat şehri', placeCount: 0 },
  { name: 'Bitlis', nameEn: 'Bitlis', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [42.1078, 38.4006] }, description: 'Vadiler içinde gelişmiş taş mimarisi, kaleleri ve Selçuklu mirasıyla bilinir', placeCount: 0 },
  { name: 'Muş', nameEn: 'Mus', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [41.4910, 38.7433] }, description: 'Malazgirt mirası, tarihî köprüleri ve camileriyle Doğu Anadolu\'nun önemli duraklarındandır', placeCount: 0 },
  { name: 'Bingöl', nameEn: 'Bingol', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [40.4983, 38.8847] }, description: 'Dağlık coğrafyası içinde kaleler, mağaralar ve eski yerleşim izleri barındırır', placeCount: 0 },
  { name: 'Tunceli', nameEn: 'Tunceli', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [39.5483, 39.1062] }, description: 'Munzur Vadisi, kaleleri ve Alevi-Bektaşi kültür hafızasıyla güçlü bir kimliğe sahiptir', placeCount: 0 },
  { name: 'Elazığ', nameEn: 'Elazig', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [39.2225, 38.6748] }, description: 'Harput merkezli tarihî dokusu ve müzeleriyle bölgenin kültür duraklarından biridir', placeCount: 0 },
  { name: 'Malatya', nameEn: 'Malatya', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [38.3552, 38.3554] }, description: 'Aslantepe\'den Osmanlı eserlerine uzanan zengin tarih katmanlarına sahip şehir', placeCount: 0 },
  { name: 'Erzincan', nameEn: 'Erzincan', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [39.4900, 39.7500] }, description: 'Fırat havzasındaki kaleleri, türbeleri ve eski ticaret yollarıyla bilinir', placeCount: 0 },
  { name: 'Hakkari', nameEn: 'Hakkari', region: 'Doğu Anadolu', location: { type: 'Point', coordinates: [43.7408, 37.5744] }, description: 'Dağlık coğrafyasında medreseler, köprüler ve sınır kültürünün izlerini taşır', placeCount: 0 },
  { name: 'Gaziantep', nameEn: 'Gaziantep', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [37.3833, 37.0662] }, description: 'Mozaikleri, kaleleri, hanları ve zengin mutfak kültürüyle Güneydoğu Anadolu’nun güçlü tarih merkezlerinden biridir', placeCount: 0 },
  { name: 'Şanlıurfa', nameEn: 'Sanliurfa', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [38.7955, 37.1674] }, description: 'Göbeklitepe, Harran ve Balıklıgöl çevresinde insanlık tarihinin en eski izlerini taşıyan şehir', placeCount: 0 },
  { name: 'Diyarbakır', nameEn: 'Diyarbakir', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [40.2306, 37.9144] }, description: 'Surları, Hevsel Bahçeleri ve çok katmanlı kent dokusuyla Mezopotamya’nın tarihî kapılarındandır', placeCount: 0 },
  { name: 'Mardin', nameEn: 'Mardin', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [40.7351, 37.3122] }, description: 'Taş mimarisi, medreseleri ve manastırlarıyla Mezopotamya ovasına bakan kültür şehri', placeCount: 0 },
  { name: 'Batman', nameEn: 'Batman', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [41.1293, 37.8812] }, description: 'Hasankeyf ve Dicle kıyısındaki tarihî mirasıyla bölgenin önemli kültür duraklarındandır', placeCount: 0 },
  { name: 'Siirt', nameEn: 'Siirt', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [41.9458, 37.9274] }, description: 'Tillo, türbeler ve camileriyle dinî ve kültürel hafızası güçlü bir şehir', placeCount: 0 },
  { name: 'Adıyaman', nameEn: 'Adiyaman', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [38.2763, 37.7648] }, description: 'Nemrut Dağı ve Kommagene mirasıyla antik dünyanın anıtsal izlerini barındırır', placeCount: 0 },
  { name: 'Kilis', nameEn: 'Kilis', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [37.1150, 36.7165] }, description: 'Höyükleri, camileri ve sınır kültürüyle eski ticaret yollarının izlerini taşıyan şehir', placeCount: 0 },
  { name: 'Şırnak', nameEn: 'Sirnak', region: 'Güneydoğu Anadolu', location: { type: 'Point', coordinates: [42.4594, 37.4187] }, description: 'Cizre merkezli tarihî mirası, medreseleri ve Dicle çevresindeki eski yerleşimleriyle bilinir', placeCount: 0 },
];

const places = [
  // İstanbul
  { name: 'Ayasofya', description: 'Bizans döneminde inşa edilmiş, sonra camiye dönüştürülmüş eşsiz yapı. Milattan sonra 537 yılında tamamlanmıştır.', category: 'historical', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9800, 41.0086] }, period: 'Byzantine', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Sultan Ahmet, Ayasofya Meydanı', images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Hagia_Sophia_Istanbul_2023.jpg/1280px-Hagia_Sophia_Istanbul_2023.jpg'], panoramaUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hagia_Sophia_(48985978757).jpg', has360: true },
  { name: 'Topkapı Sarayı', description: 'Osmanlı İmparatorluğu\'nun 400 yıllık merkezi. Padişahların yaşadığı büyük saray kompleksi.', category: 'historical', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9836, 41.0115] }, period: 'Ottoman', entryFee: 350, openingHours: '09:00 - 18:45', address: 'Cankurtaran, 34122 Fatih/İstanbul', images: [], panoramaUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Imperial_Treasury_Topkapi_panorama_2007.jpg', has360: true },
  { name: 'Sultanahmet Camii', description: 'Altı minaresiyle dünyaca ünlü Mavi Cami. 1616 yılında tamamlanmıştır.', category: 'mosque', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9772, 41.0054] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Sultan Ahmet, Atmeydanı', images: [] },
  { name: 'Kapalıçarşı', description: 'Dünyanın en büyük ve en eski kapalı çarşılarından biri. 4000\'den fazla dükkan barındırır.', category: 'historical', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9676, 41.0108] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 19:00', address: 'Beyazıt, Kalpakçılar Başı Cd.', images: [] },
  { name: 'Rumeli Hisarı', description: '1452 yılında Fatih Sultan Mehmet tarafından İstanbul kuşatmasından önce inşa ettirilen kale.', category: 'castle', city: 'İstanbul', location: { type: 'Point', coordinates: [29.0544, 41.0851] }, period: 'Ottoman', entryFee: 50, openingHours: '09:00 - 18:30', address: 'Rumeli Hisarı, Beykoz', images: [] },
  { name: 'Dolmabahce Sarayi', description: 'Bogaz kiyisinda yer alan, Osmanlinin son donem saray mimarisinin en gorkemli orneklerinden biri.', category: 'historical', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9998, 41.0390] }, period: 'Ottoman', entryFee: 450, openingHours: '09:00 - 17:30', address: 'Dolmabahce, Besiktas/Istanbul', images: [] },
  { name: 'Galata Kulesi', description: 'Beyoglunda yukselen Orta Cag kulesi, Istanbul panoramasinin en bilinen simgelerindendir.', category: 'monument', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9742, 41.0256] }, period: 'Genoese', entryFee: 650, openingHours: '08:30 - 23:00', address: 'Buyuk Hendek Cd., Beyoglu/Istanbul', images: [] },
  { name: 'Yerebatan Sarnici', description: 'Bizans doneminden kalma yeralti su sarnici; Medusa basli sutun kaideleriyle unludur.', category: 'historical', city: 'İstanbul', location: { type: 'Point', coordinates: [28.9779, 41.0084] }, period: 'Byzantine', entryFee: 600, openingHours: '09:00 - 22:00', address: 'Yerebatan Cd., Fatih/Istanbul', images: [] },

  // Ankara
  { name: 'Anıtkabir', description: 'Türkiye Cumhuriyeti\'nin kurucusu Atatürk\'ün anıt mezarı. Her yıl milyonlarca kişi ziyaret eder.', category: 'monument', city: 'Ankara', location: { type: 'Point', coordinates: [32.8362, 39.9255] }, period: 'Modern', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Anıttepe, Çankaya/Ankara', images: [], panoramaUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/An%C4%B1tkabir_%28_Atat%C3%BCrk_%29_360_Derece_Video_Panorama_Gezinti_-_360_Degree_Video.webm', has360: true },
  { name: 'Ankara Kalesi', description: 'Romalılar döneminden kalma, şehrin merkezinde yükselen tarihi kale.', category: 'castle', city: 'Ankara', location: { type: 'Point', coordinates: [32.8639, 39.9409] }, period: 'Roman', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Ulus, Altındağ/Ankara', images: [] },
  { name: 'Anadolu Medeniyetleri Müzesi', description: 'Dünyanın en önemli arkeoloji müzelerinden biri. Hitit ve Frigya eserlerini barındırır.', category: 'museum', city: 'Ankara', location: { type: 'Point', coordinates: [32.8618, 39.9397] }, period: 'Various', entryFee: 100, openingHours: '09:00 - 17:30', address: 'Gözcü Sk. No:2, Ulus/Ankara', images: [] },
  { name: 'Haci Bayram Veli Camii', description: 'Ankara Ulus bolgesinde yer alan, Haci Bayram Veli Turbesi ile birlikte ziyaret edilen onemli dini ve tarihi merkez.', category: 'mosque', city: 'Ankara', location: { type: 'Point', coordinates: [32.8185, 39.9421] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri disinda acik', address: 'Ulus/Ankara', images: [] },
  { name: 'Kocatepe Camii', description: 'Ankaranin en buyuk ve en bilinen camilerinden biri; merkezi konumu ve anitsal mimarisiyle dikkat ceker.', category: 'mosque', city: 'Ankara', location: { type: 'Point', coordinates: [32.8609, 39.9025] }, period: 'Modern', entryFee: 0, openingHours: 'Namaz vakitleri disinda acik', address: 'Kocatepe, Cankaya/Ankara', images: [] },
  { name: 'Atakule', description: 'Cankaya siluetinin simgelerinden olan kule, Ankara manzarasi icin populer bir duraktir.', category: 'monument', city: 'Ankara', location: { type: 'Point', coordinates: [32.8561, 39.8861] }, period: 'Modern', entryFee: 0, openingHours: '10:00 - 22:00', address: 'Cinnah Cd., Cankaya/Ankara', images: [] },

  // Bursa / Edirne / Canakkale - Marmara
  { name: 'Bursa Ulu Camii', description: 'Erken Osmanli mimarisinin anitsal eserlerinden biri; hat levhalari ve cok kubbeli planiyla one cikar.', category: 'mosque', city: 'Bursa', location: { type: 'Point', coordinates: [29.0619, 40.1838] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri disinda acik', address: 'Osmangazi/Bursa', images: [] },
  { name: 'Selimiye Camii', description: 'Mimar Sinanin ustalik eseri olarak kabul edilen UNESCO Dunya Mirasi camii.', category: 'mosque', city: 'Edirne', location: { type: 'Point', coordinates: [26.5593, 41.6781] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri disinda acik', address: 'Meydan Mah., Edirne Merkez', images: [] },
  { name: 'Troya Antik Kenti', description: 'Homeros destanlariyla taninan, Canakkale yakinlarindaki UNESCO Dunya Mirasi arkeolojik alan.', category: 'ruins', city: 'Canakkale', location: { type: 'Point', coordinates: [26.2391, 39.9573] }, period: 'Bronze Age', entryFee: 600, openingHours: '08:30 - 19:00', address: 'Tevfikiye, Canakkale Merkez', images: [] },

  // Konya
  { name: 'Mevlana Müzesi', description: 'Hz. Mevlana Celaleddin Rumi\'nin türbesinin bulunduğu ve Mevlevilik\'in merkezi olan müze.', category: 'museum', city: 'Konya', location: { type: 'Point', coordinates: [32.4939, 37.8714] }, period: 'Seljuk', entryFee: 0, openingHours: '09:00 - 18:30', address: 'Aziziye, Mevlana Cd., Karatay/Konya', images: [] },
  { name: 'Alaeddin Camii', description: '12. yüzyılda inşa edilmiş Selçuklu dönemi camii. Konya\'nın simgelerinden biri.', category: 'mosque', city: 'Konya', location: { type: 'Point', coordinates: [32.4861, 37.8745] }, period: 'Seljuk', entryFee: 0, openingHours: 'Namaz vakitleri', address: 'Alaeddin Tepesi, Karatay/Konya', images: [] },
  { name: 'Catalhoyuk', description: 'Neolitik donemin en onemli yerlesimlerinden biri olan UNESCO Dunya Mirasi arkeolojik alan.', category: 'ruins', city: 'Konya', location: { type: 'Point', coordinates: [32.8269, 37.6685] }, period: 'Neolithic', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Cumra/Konya', images: [] },
  { name: 'Sille', description: 'Konya yakinlarinda tarihi kiliseleri, tas sokaklari ve geleneksel dokusuyla bilinen eski yerlesim.', category: 'cultural', city: 'Konya', location: { type: 'Point', coordinates: [32.4185, 37.9282] }, period: 'Various', entryFee: 0, openingHours: 'Gunun her saati', address: 'Sille, Selcuklu/Konya', images: [] },

  // Kayseri / Eskisehir / Sivas - Ic Anadolu
  { name: 'Kayseri Kalesi', description: 'Kayseri merkezinde yer alan tarihi kale, Roma ve Selcuklu donemlerinden izler tasir.', category: 'castle', city: 'Kayseri', location: { type: 'Point', coordinates: [35.4894, 38.7211] }, period: 'Roman / Seljuk', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Cumhuriyet Meydani, Kayseri', images: [] },
  { name: 'Erciyes Dagi', description: 'Kayseri yakinlarinda yer alan volkanik dag; kis sporlari ve dogal manzarasiyla populer bir destinasyon.', category: 'cultural', city: 'Kayseri', location: { type: 'Point', coordinates: [35.5877, 38.6563] }, period: 'Natural', entryFee: 0, openingHours: 'Gunun her saati', address: 'Erciyes/Kayseri', images: [] },
  { name: 'Odunpazari Evleri', description: 'Eskisehirin tarihi dokusunu koruyan renkli geleneksel evleri ve sokaklariyla unlu bolge.', category: 'cultural', city: 'Eskisehir', location: { type: 'Point', coordinates: [30.5354, 39.7682] }, period: 'Ottoman', entryFee: 0, openingHours: 'Gunun her saati', address: 'Odunpazari/Eskisehir', images: [] },
  { name: 'Divrigi Ulu Camii ve Darussifasi', description: 'Tas isciligiyle unlu UNESCO Dunya Mirasi Selcuklu donemi cami ve sifahanesi.', category: 'mosque', city: 'Sivas', location: { type: 'Point', coordinates: [38.1219, 39.3714] }, period: 'Seljuk', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Divrigi/Sivas', images: [] },
  { name: 'Gok Medrese', description: 'Sivas merkezinde yer alan, mavi cinileri ve tas suslemeleriyle taninan Selcuklu medresesi.', category: 'historical', city: 'Sivas', location: { type: 'Point', coordinates: [37.0168, 39.7443] }, period: 'Seljuk', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Gokmedrese Cd., Sivas', images: [] },
  // Antalya
  { name: 'Aspendos Tiyatrosu', description: 'M.S. 2. yüzyılda inşa edilmiş, dünyanın en iyi korunmuş antik tiyatrosu.', category: 'ruins', city: 'Antalya', location: { type: 'Point', coordinates: [31.1717, 36.9408] }, period: 'Roman', entryFee: 200, openingHours: '08:00 - 19:00', address: 'Serik/Antalya', images: [] },
  { name: 'Perge Antik Kenti', description: 'Anadolu\'nun önemli antik şehirlerinden biri. Hadrian\'ın Kapısı ve Roma hamamları dikkat çekicidir.', category: 'ruins', city: 'Antalya', location: { type: 'Point', coordinates: [30.8536, 36.9611] }, period: 'Roman', entryFee: 150, openingHours: '08:30 - 19:30', address: 'Aksu/Antalya', images: [] },

  // Trabzon / Samsun / Sinop - Karadeniz
  { name: 'Sümela Manastırı', description: 'Karadeniz dağlarında kayaya oyulmuş Rum Ortodoks manastırı. M.S. 386 yılında kurulmuştur.', category: 'historical', city: 'Trabzon', location: { type: 'Point', coordinates: [39.6572, 40.6908] }, period: 'Byzantine', entryFee: 200, openingHours: '09:00 - 18:00', address: 'Altındere Vadisi, Maçka/Trabzon', images: [] },
  { name: 'Bandırma Gemi-Müzesi', description: 'Atatürk\'ü Samsun\'a getiren Bandırma Vapuru\'nun birebir kopyası olan müze gemi.', category: 'museum', city: 'Samsun', location: { type: 'Point', coordinates: [36.3673, 41.2734] }, period: 'Modern', entryFee: 50, openingHours: '08:00 - 17:00', address: 'Canik/Samsun', images: [] },
  { name: 'Amisos Tepesi ve Kral Mezarları', description: 'Helenistik döneme ait kral mezarları ve Samsun manzarası sunan tepe.', category: 'historical', city: 'Samsun', location: { type: 'Point', coordinates: [36.3241, 41.3191] }, period: 'Hellenistic', entryFee: 0, openingHours: '09:00 - 20:00', address: 'Atakum/Samsun', images: [] },
  { name: 'Paşa Tabyası', description: '19. yüzyılda denizden gelecek saldırılara karşı yapılmış tarihi tabya.', category: 'castle', city: 'Sinop', location: { type: 'Point', coordinates: [35.1790, 42.0167] }, period: 'Ottoman', entryFee: 20, openingHours: '09:00 - 18:00', address: 'Sinop Merkez', images: [] },
  { name: 'Vezirköprü Şahinkaya Kanyonu', description: 'Kızılırmak üzerindeki muhteşem doğa harikası kanyon.', category: 'historical', city: 'Samsun', location: { type: 'Point', coordinates: [35.4057, 41.2707] }, period: 'Natural', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Vezirköprü/Samsun', images: [] },
  { name: 'Tekkeköy Mağaraları', description: 'Karadeniz bölgesindeki en eski insan yerleşimlerinden biri olan arkeolojik alan.', category: 'ruins', city: 'Samsun', location: { type: 'Point', coordinates: [36.4617, 41.2047] }, period: 'Prehistoric', entryFee: 30, openingHours: '08:30 - 17:00', address: 'Tekkeköy/Samsun', images: [] },
  { name: 'Amazon Anıtı', description: 'Samsun\'da efsanevi Amazon kadınlarını temsil eden büyük anıt.', category: 'monument', city: 'Samsun', location: { type: 'Point', coordinates: [36.3254, 41.3238] }, period: 'Modern', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Atatürk Bulvarı, Samsun', images: [] },
  { name: 'Asar Kale', description: 'Bafra\'da Kızılırmak vadisinde Helenistik döneme ait tarihi kale kalıntıları.', category: 'castle', city: 'Samsun', location: { type: 'Point', coordinates: [35.7632, 41.3706] }, period: 'Hellenistic', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Bafra/Samsun', images: [] },
  { name: 'Bekdemir Köyü Ahşap Cami', description: 'Çivi kullanılmadan çantı tekniği ile yapılmış tarihi ahşap Karadeniz camisi.', category: 'mosque', city: 'Samsun', location: { type: 'Point', coordinates: [36.1142, 41.0187] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri', address: 'Kavak/Samsun', images: [] },
  { name: 'Çakallı Han', description: 'Selçuklu dönemine ait, İpek Yolu üzerinde bulunan tarihi kervansaray.', category: 'historical', city: 'Samsun', location: { type: 'Point', coordinates: [36.1163, 41.1414] }, period: 'Seljuk', entryFee: 0, openingHours: '09:00 - 19:00', address: 'Kavak/Samsun', images: [] },
  { name: 'Durağan Han', description: 'Tarihi ticaret yolları üzerinde yer alan görkemli bir kervansaray.', category: 'historical', city: 'Sinop', location: { type: 'Point', coordinates: [35.0561, 41.4144] }, period: 'Seljuk', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Durağan/Sinop', images: [] },
  { name: 'İlkadım Anıtı', description: 'Atatürk\'ün Samsun\'a ilk ayak bastığı yeri simgeleyen anıt.', category: 'monument', city: 'Samsun', location: { type: 'Point', coordinates: [36.3354, 41.2922] }, period: 'Modern', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Atatürk Bulvarı, Samsun', images: [] },
  { name: 'Oymaağaç Höyüğü (Nerik)', description: 'Hititlerin kutsal şehri Nerik olduğu düşünülen önemli arkeolojik kazı alanı.', category: 'ruins', city: 'Samsun', location: { type: 'Point', coordinates: [35.4293, 41.2076] }, period: 'Hittite', entryFee: 0, openingHours: '08:30 - 17:00', address: 'Vezirköprü/Samsun', images: [] },
  { name: 'Paflagon Kaya Mezarları', description: 'Antik Paflagonya bölgesine ait sarp kayalara oyulmuş tarihi mezarlar.', category: 'ruins', city: 'Samsun', location: { type: 'Point', coordinates: [35.5618, 41.2430] }, period: 'Ancient', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Vezirköprü/Samsun', images: [] },
  { name: 'Taşhan ve Taşmedrese', description: 'Vezirköprü\'nün tarihi dokusunu yansıtan Osmanlı dönemi ticaret ve eğitim merkezleri.', category: 'historical', city: 'Samsun', location: { type: 'Point', coordinates: [35.4556, 41.1442] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Vezirköprü/Samsun', images: [] },
  { name: 'Kurtuluş Yolu Başlangıç Noktası', description: 'Milli Mücadele\'nin fiilen başladığı tarihi güzergahın ilk adımı.', category: 'monument', city: 'Samsun', location: { type: 'Point', coordinates: [36.3355, 41.2899] }, period: 'Modern', entryFee: 0, openingHours: 'Gün boyu açık', address: 'Samsun Merkez', images: [] },

  // Cappadocia
  { name: 'Derinkuyu Yeraltı Şehri', description: '85 metre derinliğe inen, 20.000 kişinin yaşayabildiği Bizans dönemi yeraltı şehri.', category: 'historical', city: 'Cappadocia', location: { type: 'Point', coordinates: [34.7353, 38.3737] }, period: 'Byzantine', entryFee: 200, openingHours: '08:00 - 19:00', address: 'Derinkuyu/Nevşehir', images: [] },
  { name: 'Göreme Açık Hava Müzesi', description: 'UNESCO Dünya Mirası. Kaya kiliseleri ve fresklerle dolu vadide gezinti imkanı sunar.', category: 'museum', city: 'Cappadocia', location: { type: 'Point', coordinates: [34.8285, 38.6433] }, period: 'Byzantine', entryFee: 350, openingHours: '08:00 - 19:00', address: 'Göreme/Nevşehir', images: [] },
  { name: 'Uchisar Kalesi', description: 'Kapadokyanin en yuksek kaya kalelerinden biri; bolgenin panoramik manzarasiyla bilinir.', category: 'castle', city: 'Cappadocia', location: { type: 'Point', coordinates: [34.8053, 38.6304] }, period: 'Byzantine', entryFee: 250, openingHours: '08:00 - 19:00', address: 'Uchisar/Nevsehir', images: [] },
  { name: 'Pasabag Vadisi', description: 'Peri bacalari ve kaya olusumlariyla Kapadokyanin en populer acik hava duraklarindan biri.', category: 'ruins', city: 'Cappadocia', location: { type: 'Point', coordinates: [34.8549, 38.6770] }, period: 'Various', entryFee: 0, openingHours: 'Gunun her saati', address: 'Avanos/Nevsehir', images: [] },
  { name: 'Zelve Acik Hava Muzesi', description: 'Kaya oyma yasam alanlari ve kiliseleriyle Kapadokyanin tarihi dokusunu gosteren acik hava muzesi.', category: 'museum', city: 'Cappadocia', location: { type: 'Point', coordinates: [34.8653, 38.6657] }, period: 'Byzantine', entryFee: 280, openingHours: '08:00 - 19:00', address: 'Avanos/Nevsehir', images: [] },
  { name: 'Kaymakli Yeralti Sehri', description: 'Kapadokyada cok katli savunma ve yasam alanlariyla bilinen tarihi yeralti sehri.', category: 'historical', city: 'Cappadocia', location: { type: 'Point', coordinates: [34.7525, 38.4599] }, period: 'Byzantine', entryFee: 300, openingHours: '08:00 - 19:00', address: 'Kaymakli/Nevsehir', images: [] },

  // Ege Bölgesi (İzmir, Aydın, Denizli, Muğla)
  { name: 'Efes Antik Kenti', description: 'UNESCO Dünya Mirası. Antik çağın en önemli liman şehirlerinden ve Roma İmparatorluğu\'nun Asya eyaleti başkenti.', category: 'ruins', city: 'İzmir', location: { type: 'Point', coordinates: [27.3411, 37.9411] }, period: 'Roman', entryFee: 400, openingHours: '08:00 - 18:30', address: 'Selçuk/İzmir', images: [], has360: true, panoramaUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Celsus_Library_Ephesus_Turkey.jpg' },
  { name: 'Hierapolis Antik Kenti', description: 'Pamukkale travertenlerinin hemen yanında bulunan kutsal Frigya kenti.', category: 'ruins', city: 'Denizli', location: { type: 'Point', coordinates: [29.1258, 37.9258] }, period: 'Roman', entryFee: 400, openingHours: '08:00 - 19:00', address: 'Pamukkale/Denizli', images: [] },
  { name: 'Bodrum Kalesi', description: '15. yüzyılda St. Jean Şövalyeleri tarafından inşa edilen ve Sualtı Arkeoloji Müzesi\'ne ev sahipliği yapan kale.', category: 'castle', city: 'Muğla', location: { type: 'Point', coordinates: [27.4288, 37.0316] }, period: 'Medieval', entryFee: 350, openingHours: '08:30 - 18:00', address: 'Bodrum/Muğla', images: [] },
  { name: 'Afrodisias Antik Kenti', description: 'Antik çağın en ünlü heykeltıraşlık okullarından birine sahip, Roma dönemi kenti.', category: 'ruins', city: 'Aydın', location: { type: 'Point', coordinates: [28.7230, 37.7088] }, period: 'Roman', entryFee: 200, openingHours: '08:30 - 18:30', address: 'Karacasu/Aydın', images: [] },
  { name: 'Agora Ören Yeri', description: 'İzmir\'in kalbinde yer alan, antik Roma dönemi çarşısı ve toplanma alanı.', category: 'ruins', city: 'İzmir', location: { type: 'Point', coordinates: [27.1378, 38.4173] }, period: 'Roman', entryFee: 130, openingHours: '08:30 - 17:30', address: 'Namazgah, İzmir', images: [] },

  // Doğu Anadolu
  { name: 'Çifte Minareli Medrese', description: 'Erzurum’un en tanınan Selçuklu eserlerinden biridir. Taç kapısı ve çift minaresiyle kentin tarihî siluetini belirler.', category: 'historical', city: 'Erzurum', location: { type: 'Point', coordinates: [41.2791, 39.9058] }, period: 'Seljuk', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Sultanmelik Mah., Erzurum Merkez', images: [], approved: true },
  { name: 'Yakutiye Medresesi', description: 'İlhanlı döneminden kalan yapı, taş işçiliği ve müze işleviyle Erzurum’un önemli kültür duraklarındandır.', category: 'museum', city: 'Erzurum', location: { type: 'Point', coordinates: [41.2745, 39.9047] }, period: 'Ilkhanid', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Lalapaşa Mah., Erzurum', images: [], approved: true },
  { name: 'Erzurum Kalesi', description: 'Şehrin merkezinde yükselen kale, Bizans ve Osmanlı dönemlerinde güçlendirilmiş savunma yapılarından biridir.', category: 'castle', city: 'Erzurum', location: { type: 'Point', coordinates: [41.2786, 39.9066] }, period: 'Byzantine / Ottoman', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Sultanmelik Mah., Erzurum', images: [], approved: true },
  { name: 'Üç Kümbetler', description: 'Anadolu’daki anıt mezar mimarisinin güçlü örneklerindendir. Erzurum’un Selçuklu ve Saltuklu mirasını görünür kılar.', category: 'monument', city: 'Erzurum', location: { type: 'Point', coordinates: [41.2814, 39.9028] }, period: 'Saltukid / Seljuk', entryFee: 0, openingHours: 'Günün her saati', address: 'Sultanmelik Mah., Erzurum', images: [], approved: true },
  { name: 'Aziziye Tabyaları', description: 'Osmanlı-Rus savaşları sırasında Erzurum savunmasının sembol alanlarından biridir. Nene Hatun anlatısıyla kent hafızasında özel yer tutar.', category: 'historical', city: 'Erzurum', location: { type: 'Point', coordinates: [41.3408, 39.9152] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Aziziye, Erzurum', images: [], approved: true },
  { name: 'Erzurum Kongre Binası', description: 'Milli Mücadele’nin dönüm noktalarından Erzurum Kongresi burada toplanmıştır. Yapı bugün yakın tarih hafızasını yaşatan bir müze niteliğindedir.', category: 'museum', city: 'Erzurum', location: { type: 'Point', coordinates: [41.2677, 39.9068] }, period: 'Republican Era', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Kongre Cd., Erzurum', images: [], approved: true },
  { name: 'Lala Mustafa Paşa Camii', description: 'Erzurum merkezde yer alan Osmanlı camisi, klasik dönem mimarisinin şehirdeki önemli temsilcilerindendir.', category: 'mosque', city: 'Erzurum', location: { type: 'Point', coordinates: [41.2757, 39.9041] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Lalapaşa Mah., Erzurum', images: [], approved: true },

  { name: 'Ani Harabeleri', description: 'Türkiye-Ermenistan sınırında yer alan Ani, Orta Çağ’ın görkemli kentlerinden biridir. Kiliseleri, surları ve taş işçiliğiyle UNESCO Dünya Mirası listesindedir.', category: 'ruins', city: 'Kars', location: { type: 'Point', coordinates: [43.5724, 40.5076] }, period: 'Medieval', entryFee: 0, openingHours: '08:00 - 19:00', address: 'Ocaklı Köyü, Kars', images: [], approved: true },
  { name: 'Kars Kalesi', description: 'Kars merkezinde yükselen kale, şehrin savunma tarihini ve sınır kenti kimliğini yansıtır.', category: 'castle', city: 'Kars', location: { type: 'Point', coordinates: [43.0947, 40.6082] }, period: 'Medieval / Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Kaleiçi Mah., Kars', images: [], approved: true },
  { name: 'Fethiye Camii', description: 'Baltık üslubundaki eski kilise yapısı, Cumhuriyet döneminde camiye dönüştürülmüştür. Kars’ın çok katmanlı mimari belleğini gösterir.', category: 'mosque', city: 'Kars', location: { type: 'Point', coordinates: [43.0955, 40.6037] }, period: 'Russian / Republican Era', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Ortakapı Mah., Kars', images: [], approved: true },
  { name: 'Taş Köprü', description: 'Kars Çayı üzerindeki tarihî köprü, kale çevresindeki eski kent dokusunun önemli parçalarından biridir.', category: 'historical', city: 'Kars', location: { type: 'Point', coordinates: [43.0965, 40.6070] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Kaleiçi, Kars', images: [], approved: true },
  { name: 'Kümbet Camii', description: 'On İki Havariler Kilisesi olarak da bilinen yapı, Kars’ın Orta Çağ mirasının en dikkat çekici örneklerindendir.', category: 'mosque', city: 'Kars', location: { type: 'Point', coordinates: [43.0951, 40.6078] }, period: 'Medieval', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Kaleiçi Mah., Kars', images: [], approved: true },
  { name: 'Namık Kemal Evi', description: 'Şair Namık Kemal’in çocukluk yıllarıyla ilişkilendirilen ev, Kars’ın kültür tarihi açısından anlamlı bir duraktır.', category: 'museum', city: 'Kars', location: { type: 'Point', coordinates: [43.0915, 40.6063] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Kars Merkez', images: [], approved: true },

  { name: 'Akdamar Kilisesi', description: 'Van Gölü’ndeki Akdamar Adası’nda yer alan kilise, dış cephe kabartmalarıyla ünlüdür. Orta Çağ Ermeni sanatının Anadolu’daki seçkin örneklerindendir.', category: 'historical', city: 'Van', location: { type: 'Point', coordinates: [43.0367, 38.3400] }, period: 'Medieval Armenian', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Akdamar Adası, Gevaş/Van', images: [], approved: true },
  { name: 'Van Kalesi', description: 'Urartu Krallığı’nın başkenti Tuşpa’ya hâkim kaya kalesidir. Van Gölü kıyısındaki konumuyla bölgenin en önemli arkeolojik alanlarındandır.', category: 'castle', city: 'Van', location: { type: 'Point', coordinates: [43.3386, 38.5017] }, period: 'Urartian', entryFee: 0, openingHours: '08:00 - 19:00', address: 'İskele Mah., Van', images: [], approved: true },
  { name: 'Hoşap Kalesi', description: 'Güzelsu’da sarp bir kaya üzerinde kurulan kale, bölgedeki Osmanlı dönemi savunma mimarisinin görkemli örneklerindendir.', category: 'castle', city: 'Van', location: { type: 'Point', coordinates: [44.1616, 38.3273] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Güzelsu, Gürpınar/Van', images: [], approved: true },
  { name: 'Çavuştepe Kalesi', description: 'Urartu dönemine ait Çavuştepe, tapınakları ve surlarıyla Van çevresinin arkeolojik önemini gösterir.', category: 'ruins', city: 'Van', location: { type: 'Point', coordinates: [43.7984, 38.2643] }, period: 'Urartian', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Çavuştepe, Gürpınar/Van', images: [], approved: true },
  { name: 'Van Müzesi', description: 'Urartu eserleri başta olmak üzere Van Havzası’nın arkeolojik ve etnografik mirasını sergileyen önemli bir müzedir.', category: 'museum', city: 'Van', location: { type: 'Point', coordinates: [43.3509, 38.5010] }, period: 'Various', entryFee: 0, openingHours: '09:00 - 17:00', address: 'İskele Cd., Van', images: [], approved: true },
  { name: 'Hüsrev Paşa Camii', description: 'Mimar Sinan ekolünün Van’daki önemli Osmanlı eserlerinden biridir. Eski Van bölgesindeki tarihî dokunun parçasıdır.', category: 'mosque', city: 'Van', location: { type: 'Point', coordinates: [43.3396, 38.5004] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Eski Van, Van', images: [], approved: true },

  { name: 'İshak Paşa Sarayı', description: 'Doğubayazıt yakınlarında yükselen saray, Osmanlı, Selçuklu ve İran etkilerini bir araya getirir. Doğu Anadolu’nun en etkileyici anıtsal yapılarındandır.', category: 'historical', city: 'Ağrı', location: { type: 'Point', coordinates: [44.1286, 39.5205] }, period: 'Ottoman', entryFee: 0, openingHours: '08:30 - 18:00', address: 'Doğubayazıt/Ağrı', images: [], approved: true },
  { name: 'Doğubayazıt Kalesi', description: 'İshak Paşa Sarayı yakınındaki kale kalıntıları, bölgenin eski savunma ve yerleşim tarihini yansıtır.', category: 'castle', city: 'Ağrı', location: { type: 'Point', coordinates: [44.1262, 39.5219] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Doğubayazıt/Ağrı', images: [], approved: true },
  { name: 'Ahmed-i Hani Türbesi', description: 'Kürt edebiyatının önemli isimlerinden Ahmed-i Hani’ye adanan türbe, Doğubayazıt’ın kültürel hafızasında özel yer tutar.', category: 'monument', city: 'Ağrı', location: { type: 'Point', coordinates: [44.1246, 39.5202] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Doğubayazıt/Ağrı', images: [], approved: true },
  { name: 'Durupınar / Nuh’un Gemisi İzleri', description: 'Doğubayazıt çevresindeki doğal oluşum, Nuh’un Gemisi anlatılarıyla ilişkilendirilen tartışmalı ama popüler bir ziyaret noktasıdır.', category: 'cultural', city: 'Ağrı', location: { type: 'Point', coordinates: [44.2347, 39.4408] }, period: 'Natural / Cultural', entryFee: 0, openingHours: 'Günün her saati', address: 'Telçeker Köyü, Doğubayazıt/Ağrı', images: [], approved: true },

  { name: 'Karakale Harabesi', description: 'Aras Vadisi yakınındaki kale kalıntısı, Iğdır çevresinin eski savunma hatlarından izler taşır.', category: 'ruins', city: 'Iğdır', location: { type: 'Point', coordinates: [43.9837, 39.9695] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Karakale, Iğdır', images: [], approved: true },
  { name: 'Iğdır Soykırım Anıt-Müzesi', description: 'Iğdır merkezde yer alan anıt-müze, yakın dönem hafıza ve anma kültürü açısından önemli bir yapıdır.', category: 'museum', city: 'Iğdır', location: { type: 'Point', coordinates: [44.0424, 39.9168] }, period: 'Modern', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Iğdır Merkez', images: [], approved: true },
  { name: 'Harmandöven Kervansarayı', description: 'Tuzluca çevresindeki tarihî kervansaray, eski ticaret yollarının bölgedeki izlerini gösterir.', category: 'historical', city: 'Iğdır', location: { type: 'Point', coordinates: [43.6546, 40.0294] }, period: 'Seljuk', entryFee: 0, openingHours: 'Günün her saati', address: 'Tuzluca/Iğdır', images: [], approved: true },

  { name: 'Ardahan Kalesi', description: 'Kura Nehri kıyısında yer alan kale, Ardahan’ın tarihî merkezini belirleyen ana yapılardandır.', category: 'castle', city: 'Ardahan', location: { type: 'Point', coordinates: [42.7013, 41.1084] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Ardahan Merkez', images: [], approved: true },
  { name: 'Şeytan Kalesi', description: 'Çıldır yakınlarında sarp kayalık üzerinde bulunan kale, dramatik konumu ve Orta Çağ savunma mimarisiyle dikkat çeker.', category: 'castle', city: 'Ardahan', location: { type: 'Point', coordinates: [43.1078, 41.2643] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Yıldırımtepe, Çıldır/Ardahan', images: [], approved: true },
  { name: 'Kinzi Kalesi', description: 'Ardahan çevresindeki eski savunma noktalarından biri olan Kinzi Kalesi, bölgenin sınır tarihine işaret eder.', category: 'castle', city: 'Ardahan', location: { type: 'Point', coordinates: [42.8598, 41.1114] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Ardahan çevresi', images: [], approved: true },

  { name: 'Bitlis Kalesi', description: 'Bitlis merkezde sarp kayalık üzerinde yer alan kale, kentin vadiler içindeki tarihî çekirdeğine hâkimdir.', category: 'castle', city: 'Bitlis', location: { type: 'Point', coordinates: [42.1085, 38.3995] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Bitlis Merkez', images: [], approved: true },
  { name: 'Ahlat Selçuklu Mezarlığı', description: 'Anadolu’nun en etkileyici tarihî mezarlık alanlarından biridir. Anıtsal mezar taşları Selçuklu taş işçiliğinin seçkin örneklerini sunar.', category: 'monument', city: 'Bitlis', location: { type: 'Point', coordinates: [42.4917, 38.7536] }, period: 'Seljuk', entryFee: 0, openingHours: '08:00 - 19:00', address: 'Ahlat/Bitlis', images: [], approved: true },
  { name: 'Emir Bayındır Kümbeti', description: 'Ahlat’taki kümbet, zarif taş süslemeleri ve anıt mezar geleneğiyle dikkat çeker.', category: 'monument', city: 'Bitlis', location: { type: 'Point', coordinates: [42.4939, 38.7562] }, period: 'Akkoyunlu', entryFee: 0, openingHours: 'Günün her saati', address: 'Ahlat/Bitlis', images: [], approved: true },
  { name: 'İhlasiye Medresesi', description: 'Bitlis’teki medrese, İslam eğitim mimarisinin bölgedeki önemli tarihî örneklerindendir.', category: 'historical', city: 'Bitlis', location: { type: 'Point', coordinates: [42.1097, 38.3991] }, period: 'Seljuk / Ottoman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Bitlis Merkez', images: [], approved: true },
  { name: 'El Aman Hanı', description: 'Bitlis-Tatvan yolu üzerindeki büyük han, eski kervan yollarının bölgedeki en görkemli yapılarındandır.', category: 'historical', city: 'Bitlis', location: { type: 'Point', coordinates: [42.1978, 38.4725] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Rahva, Bitlis', images: [], approved: true },

  { name: 'Murat Köprüsü', description: 'Muş yakınlarında Murat Nehri üzerinde yer alan tarihî köprü, eski ulaşım ağlarının önemli bir parçasıdır.', category: 'historical', city: 'Muş', location: { type: 'Point', coordinates: [41.4054, 38.7648] }, period: 'Seljuk / Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Muş Merkez', images: [], approved: true },
  { name: 'Muş Ulu Camii', description: 'Muş merkezde bulunan cami, şehirdeki İslami mimari mirasın önemli yapılarından biridir.', category: 'mosque', city: 'Muş', location: { type: 'Point', coordinates: [41.4927, 38.7357] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Muş Merkez', images: [], approved: true },
  { name: 'Arak Manastırı', description: 'Muş çevresindeki eski manastır kalıntısı, bölgenin çok kültürlü dinî mirasını yansıtır.', category: 'ruins', city: 'Muş', location: { type: 'Point', coordinates: [41.3615, 38.6345] }, period: 'Medieval Armenian', entryFee: 0, openingHours: 'Günün her saati', address: 'Kepenek Köyü, Muş', images: [], approved: true },
  { name: 'Malazgirt Meydan Muharebesi Tarihi Milli Parkı', description: '1071 Malazgirt Meydan Muharebesi’nin anısını yaşatan alan, Anadolu tarihinin dönüm noktalarından birini temsil eder.', category: 'monument', city: 'Muş', location: { type: 'Point', coordinates: [42.5358, 39.1462] }, period: 'Seljuk', entryFee: 0, openingHours: 'Günün her saati', address: 'Malazgirt/Muş', images: [], approved: true },

  { name: 'Kiğı Kalesi', description: 'Kiğı’da yer alan kale kalıntıları, Bingöl çevresindeki eski yerleşim ve savunma tarihine ışık tutar.', category: 'castle', city: 'Bingöl', location: { type: 'Point', coordinates: [40.3485, 39.3137] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Kiğı/Bingöl', images: [], approved: true },
  { name: 'Zağ Mağaraları', description: 'Kayalara oyulmuş mağara yerleşimleri, Bingöl’ün eski yaşam alanlarına ve savunma düzenlerine dair izler sunar.', category: 'ruins', city: 'Bingöl', location: { type: 'Point', coordinates: [40.5767, 38.9561] }, period: 'Ancient / Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Zağ Köyü, Bingöl', images: [], approved: true },

  { name: 'Pertek Kalesi', description: 'Keban Baraj Gölü üzerinde ada görünümündeki kale, Pertek’in en bilinen tarihî simgesidir.', category: 'castle', city: 'Tunceli', location: { type: 'Point', coordinates: [39.3246, 38.8615] }, period: 'Medieval / Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Pertek/Tunceli', images: [], approved: true },
  { name: 'Çemişgezek Kalesi', description: 'Fırat havzasına hâkim konumdaki kale kalıntıları, Çemişgezek’in eski yerleşim dokusunu yansıtır.', category: 'castle', city: 'Tunceli', location: { type: 'Point', coordinates: [38.9147, 39.0628] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Çemişgezek/Tunceli', images: [], approved: true },
  { name: 'Munzur Vadisi', description: 'Munzur Vadisi, doğal peyzajının yanında yerel inanç ve ziyaret kültürüyle Tunceli kimliğinin merkezindedir.', category: 'cultural', city: 'Tunceli', location: { type: 'Point', coordinates: [39.4205, 39.2630] }, period: 'Natural / Cultural', entryFee: 0, openingHours: 'Günün her saati', address: 'Munzur Vadisi Milli Parkı, Tunceli', images: [], approved: true },

  { name: 'Harput Kalesi', description: 'Harput’un yüksek kayalık alanında bulunan kale, Elazığ’ın tarihî çekirdeğinin en güçlü simgesidir.', category: 'castle', city: 'Elazığ', location: { type: 'Point', coordinates: [39.2564, 38.7054] }, period: 'Urartian / Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Harput, Elazığ', images: [], approved: true },
  { name: 'Harput Ulu Camii', description: 'Anadolu’nun eski camilerinden biri kabul edilen yapı, eğik minaresi ve tarihî dokusuyla dikkat çeker.', category: 'mosque', city: 'Elazığ', location: { type: 'Point', coordinates: [39.2576, 38.7044] }, period: 'Artuqid', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Harput, Elazığ', images: [], approved: true },
  { name: 'Sarahatun Camii', description: 'Akkoyunlu dönemine uzanan cami, Harput’un dinî ve mimari mirasının önemli parçalarındandır.', category: 'mosque', city: 'Elazığ', location: { type: 'Point', coordinates: [39.2583, 38.7040] }, period: 'Akkoyunlu / Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Harput, Elazığ', images: [], approved: true },
  { name: 'Arap Baba Türbesi', description: 'Harput’ta yer alan türbe, yerel inanç ve ziyaret geleneğinde güçlü bir yere sahiptir.', category: 'monument', city: 'Elazığ', location: { type: 'Point', coordinates: [39.2571, 38.7049] }, period: 'Seljuk', entryFee: 0, openingHours: 'Günün her saati', address: 'Harput, Elazığ', images: [], approved: true },
  { name: 'Elazığ Arkeoloji ve Etnografya Müzesi', description: 'Elazığ ve çevresinin arkeolojik buluntularını ve geleneksel yaşam kültürünü tanıtan önemli bir müzedir.', category: 'museum', city: 'Elazığ', location: { type: 'Point', coordinates: [39.2269, 38.6813] }, period: 'Various', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Elazığ Merkez', images: [], approved: true },

  { name: 'Aslantepe Höyüğü', description: 'UNESCO Dünya Mirası olan Aslantepe, devletleşme süreçlerini gösteren çok önemli bir arkeolojik merkezdir.', category: 'ruins', city: 'Malatya', location: { type: 'Point', coordinates: [38.3604, 38.3848] }, period: 'Chalcolithic / Hittite', entryFee: 0, openingHours: '08:30 - 17:30', address: 'Orduzu, Malatya', images: [], approved: true },
  { name: 'Battalgazi Ulu Camii', description: 'Eski Malatya’da yer alan cami, Anadolu Selçuklu mimarisinin önemli örnekleri arasındadır.', category: 'mosque', city: 'Malatya', location: { type: 'Point', coordinates: [38.3678, 38.4243] }, period: 'Seljuk', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Battalgazi/Malatya', images: [], approved: true },
  { name: 'Silahtar Mustafa Paşa Kervansarayı', description: 'Battalgazi’deki kervansaray, Osmanlı dönemi ticaret yollarının Malatya’daki güçlü izlerinden biridir.', category: 'historical', city: 'Malatya', location: { type: 'Point', coordinates: [38.3652, 38.4238] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Battalgazi/Malatya', images: [], approved: true },
  { name: 'Malatya Müzesi', description: 'Malatya ve çevresinden çıkan arkeolojik eserleri sergileyen müze, Aslantepe başta olmak üzere bölgenin tarihini görünür kılar.', category: 'museum', city: 'Malatya', location: { type: 'Point', coordinates: [38.3210, 38.3529] }, period: 'Various', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Kernek, Malatya', images: [], approved: true },
  { name: 'Somuncu Baba Türbesi', description: 'Darende’deki türbe ve külliye, dini ziyaret kültürü ve tarihî çevresiyle Malatya’nın önemli duraklarındandır.', category: 'monument', city: 'Malatya', location: { type: 'Point', coordinates: [37.5056, 38.5456] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Darende/Malatya', images: [], approved: true },

  { name: 'Mama Hatun Türbesi', description: 'Tercan’daki anıt mezar, Saltuklu döneminin en özgün mimari eserlerinden biridir.', category: 'monument', city: 'Erzincan', location: { type: 'Point', coordinates: [40.3910, 39.7791] }, period: 'Saltukid', entryFee: 0, openingHours: 'Günün her saati', address: 'Tercan/Erzincan', images: [], approved: true },
  { name: 'Kemah Kalesi', description: 'Fırat Vadisi’ne hâkim konumdaki kale, Erzincan çevresinin stratejik tarihini yansıtır.', category: 'castle', city: 'Erzincan', location: { type: 'Point', coordinates: [39.0314, 39.5968] }, period: 'Medieval / Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Kemah/Erzincan', images: [], approved: true },
  { name: 'Terzibaba Türbesi', description: 'Erzincan merkezdeki türbe, kentin manevi hafızasında önemli bir ziyaret noktasıdır.', category: 'monument', city: 'Erzincan', location: { type: 'Point', coordinates: [39.5068, 39.7521] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Erzincan Merkez', images: [], approved: true },

  { name: 'Meydan Medresesi', description: 'Hakkari merkezde bulunan medrese, bölgenin taş mimari geleneğini ve eğitim tarihini yansıtır.', category: 'historical', city: 'Hakkari', location: { type: 'Point', coordinates: [43.7402, 37.5731] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Biçer Mah., Hakkari', images: [], approved: true },
  { name: 'Hakkari Taş Köprü', description: 'Zap Suyu çevresindeki tarihî taş köprü, Hakkari’nin eski ulaşım yollarından günümüze kalan önemli bir yapıdır.', category: 'historical', city: 'Hakkari', location: { type: 'Point', coordinates: [43.7025, 37.5457] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Hakkari Merkez', images: [], approved: true },

  // Güneydoğu Anadolu
  { name: 'Zeugma Mozaik Müzesi', description: 'Gaziantep’teki müze, Zeugma Antik Kenti’nden çıkarılan mozaikleri ve bölgenin Roma dönemi sanatını sergiler.', category: 'museum', city: 'Gaziantep', location: { type: 'Point', coordinates: [37.3832, 37.0753] }, period: 'Roman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Mithatpaşa Mah., Gaziantep', images: [], approved: true },
  { name: 'Gaziantep Kalesi', description: 'Şehir merkezinde yükselen kale, Roma döneminden Osmanlı’ya uzanan savunma tarihinin izlerini taşır.', category: 'castle', city: 'Gaziantep', location: { type: 'Point', coordinates: [37.3839, 37.0667] }, period: 'Roman / Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Seferpaşa Mah., Gaziantep', images: [], approved: true },
  { name: 'Bakırcılar Çarşısı', description: 'Geleneksel bakır işçiliğinin sürdüğü çarşı, Gaziantep’in yaşayan zanaat ve ticaret kültürünü gösterir.', category: 'cultural', city: 'Gaziantep', location: { type: 'Point', coordinates: [37.3821, 37.0638] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 19:00', address: 'Şahinbey/Gaziantep', images: [], approved: true },
  { name: 'Zincirli Bedesten', description: 'Osmanlı döneminden kalan bedesten, Gaziantep’in tarihî ticaret dokusunun önemli yapılarındandır.', category: 'historical', city: 'Gaziantep', location: { type: 'Point', coordinates: [37.3807, 37.0634] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Şahinbey/Gaziantep', images: [], approved: true },
  { name: 'Emine Göğüş Mutfak Müzesi', description: 'Gaziantep mutfak kültürünü ve geleneksel yaşam pratiklerini anlatan müze, kentin UNESCO gastronomi kimliğiyle ilişkilidir.', category: 'museum', city: 'Gaziantep', location: { type: 'Point', coordinates: [37.3793, 37.0649] }, period: 'Ottoman / Modern', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Bey Mah., Gaziantep', images: [], approved: true },
  { name: 'Rumkale', description: 'Fırat ve Merzimen çaylarının birleştiği noktada yükselen Rumkale, etkileyici konumu ve Orta Çağ mirasıyla tanınır.', category: 'castle', city: 'Gaziantep', location: { type: 'Point', coordinates: [37.8690, 37.2704] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Yavuzeli/Gaziantep', images: [], approved: true },

  { name: 'Göbeklitepe', description: 'Neolitik döneme ait anıtsal yapılarıyla insanlık tarihinin en eski kült merkezlerinden biridir. UNESCO Dünya Mirası listesindedir.', category: 'ruins', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [38.9225, 37.2231] }, period: 'Neolithic', entryFee: 0, openingHours: '08:30 - 18:00', address: 'Örencik, Şanlıurfa', images: [], approved: true },
  { name: 'Balıklıgöl', description: 'Şanlıurfa merkezdeki kutsal göl ve çevresi, inanç turizmi ve şehir kültürünün en önemli odaklarından biridir.', category: 'cultural', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [38.7891, 37.1492] }, period: 'Various', entryFee: 0, openingHours: 'Günün her saati', address: 'Eyyübiye/Şanlıurfa', images: [], approved: true },
  { name: 'Urfa Kalesi', description: 'Balıklıgöl’e hâkim tepede yer alan kale, şehir merkezinin antik ve Orta Çağ savunma dokusunu yansıtır.', category: 'castle', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [38.7887, 37.1471] }, period: 'Ancient / Medieval', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Eyyübiye/Şanlıurfa', images: [], approved: true },
  { name: 'Haleplibahçe Mozaik Müzesi', description: 'Roma dönemine ait mozaikleriyle bilinen müze, Şanlıurfa’nın antik kent yaşamını görünür kılar.', category: 'museum', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [38.7867, 37.1525] }, period: 'Roman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Haleplibahçe, Şanlıurfa', images: [], approved: true },
  { name: 'Harran Antik Kenti', description: 'Konik kubbeli evleri ve antik üniversite geleneğiyle Harran, Mezopotamya kültürünün önemli merkezlerindendir.', category: 'ruins', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [39.0314, 36.8631] }, period: 'Ancient / Islamic', entryFee: 0, openingHours: 'Günün her saati', address: 'Harran/Şanlıurfa', images: [], approved: true },
  { name: 'Şuayb Antik Kenti', description: 'Harran Ovası çevresindeki antik yerleşim, kaya mekânları ve yerel inanç anlatılarıyla dikkat çeker.', category: 'ruins', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [39.4966, 36.7276] }, period: 'Roman / Late Antique', entryFee: 0, openingHours: 'Günün her saati', address: 'Harran/Şanlıurfa', images: [], approved: true },
  { name: 'Soğmatar Antik Kenti', description: 'Ay ve gezegen kültleriyle ilişkilendirilen Soğmatar, kaya anıtları ve kutsal alanlarıyla öne çıkar.', category: 'ruins', city: 'Şanlıurfa', location: { type: 'Point', coordinates: [39.4669, 36.9085] }, period: 'Roman / Late Antique', entryFee: 0, openingHours: 'Günün her saati', address: 'Eyyübiye/Şanlıurfa', images: [], approved: true },

  { name: 'Diyarbakır Surları', description: 'Bazalt taşlı surlar, Diyarbakır’ın tarihî kent kimliğinin en güçlü simgesidir. Hevsel Bahçeleri ile birlikte UNESCO Dünya Mirası kapsamındadır.', category: 'historical', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.2319, 37.9128] }, period: 'Roman / Byzantine / Islamic', entryFee: 0, openingHours: 'Günün her saati', address: 'Sur/Diyarbakır', images: [], approved: true },
  { name: 'Hevsel Bahçeleri', description: 'Dicle kıyısındaki tarihî tarım peyzajı, Diyarbakır’ın kent yaşamı ve ekolojik hafızası için büyük önem taşır.', category: 'cultural', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.2439, 37.9069] }, period: 'Various', entryFee: 0, openingHours: 'Günün her saati', address: 'Sur/Diyarbakır', images: [], approved: true },
  { name: 'Ulu Camii', description: 'Diyarbakır Ulu Camii, Anadolu’nun en eski camilerinden biri kabul edilir ve farklı dönemlerin mimari izlerini taşır.', category: 'mosque', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.2310, 37.9141] }, period: 'Islamic / Seljuk', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Cami Kebir Mah., Diyarbakır', images: [], approved: true },
  { name: 'Hasan Paşa Hanı', description: 'Osmanlı döneminden kalan han, Diyarbakır’ın tarihî ticaret ve konaklama kültürünün canlı örneklerindendir.', category: 'historical', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.2304, 37.9146] }, period: 'Ottoman', entryFee: 0, openingHours: '09:00 - 20:00', address: 'Sur/Diyarbakır', images: [], approved: true },
  { name: 'On Gözlü Köprü', description: 'Dicle Nehri üzerindeki tarihî köprü, Diyarbakır’ın ulaşım ve mühendislik mirasının önemli parçalarındandır.', category: 'historical', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.2368, 37.8877] }, period: 'Artuqid', entryFee: 0, openingHours: 'Günün her saati', address: 'Sur/Diyarbakır', images: [], approved: true },
  { name: 'İçkale Müze Kompleksi', description: 'Eski yönetim merkezinde yer alan kompleks, Diyarbakır’ın arkeolojik ve kent tarihini sergiler.', category: 'museum', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.2381, 37.9155] }, period: 'Various', entryFee: 0, openingHours: '09:00 - 17:00', address: 'İçkale, Sur/Diyarbakır', images: [], approved: true },
  { name: 'Zerzevan Kalesi', description: 'Roma İmparatorluğu’nun sınır garnizonlarından biri olan Zerzevan, Mithras tapınağıyla da dikkat çeker.', category: 'ruins', city: 'Diyarbakır', location: { type: 'Point', coordinates: [40.6629, 37.8978] }, period: 'Roman', entryFee: 0, openingHours: '08:30 - 18:00', address: 'Çınar/Diyarbakır', images: [], approved: true },

  { name: 'Mardin Eski Şehir', description: 'Teraslı taş evleri, dar sokakları ve ovaya bakan siluetiyle Mardin’in tarihî çekirdeğidir.', category: 'cultural', city: 'Mardin', location: { type: 'Point', coordinates: [40.7358, 37.3130] }, period: 'Various', entryFee: 0, openingHours: 'Günün her saati', address: 'Artuklu/Mardin', images: [], approved: true },
  { name: 'Deyrulzafaran Manastırı', description: 'Süryani Ortodoks geleneğinin önemli merkezlerinden olan manastır, Mardin’in çok kültürlü dinî mirasını yansıtır.', category: 'historical', city: 'Mardin', location: { type: 'Point', coordinates: [40.7921, 37.3201] }, period: 'Late Antique / Syriac', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Artuklu/Mardin', images: [], approved: true },
  { name: 'Kasımiye Medresesi', description: 'Artuklu ve Akkoyunlu mimarisinin görkemli örneklerinden olan medrese, taş işçiliği ve avlusuyla öne çıkar.', category: 'historical', city: 'Mardin', location: { type: 'Point', coordinates: [40.7229, 37.3066] }, period: 'Artuqid / Akkoyunlu', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Artuklu/Mardin', images: [], approved: true },
  { name: 'Zinciriye Medresesi', description: 'Mardin’in eski şehir dokusunda yer alan medrese, anıtsal kapısı ve manzarasıyla bilinir.', category: 'historical', city: 'Mardin', location: { type: 'Point', coordinates: [40.7375, 37.3142] }, period: 'Artuqid', entryFee: 0, openingHours: '09:00 - 18:00', address: 'Artuklu/Mardin', images: [], approved: true },
  { name: 'Mardin Ulu Camii', description: 'Artuklu döneminin önemli camilerinden olan yapı, minaresi ve taş süslemeleriyle Mardin siluetinde özel yer tutar.', category: 'mosque', city: 'Mardin', location: { type: 'Point', coordinates: [40.7370, 37.3124] }, period: 'Artuqid', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Ulu Cami Mah., Mardin', images: [], approved: true },
  { name: 'Dara Antik Kenti', description: 'Roma’nın doğu sınırındaki önemli garnizon kentlerinden Dara, sarnıçları ve nekropol alanıyla tanınır.', category: 'ruins', city: 'Mardin', location: { type: 'Point', coordinates: [40.9544, 37.1796] }, period: 'Roman / Byzantine', entryFee: 0, openingHours: 'Günün her saati', address: 'Oğuz, Artuklu/Mardin', images: [], approved: true },
  { name: 'Mor Gabriel Manastırı', description: 'Dünyanın en eski Süryani manastırlarından biri olan Mor Gabriel, Tur Abdin bölgesinin dinî hafızasında merkezî yere sahiptir.', category: 'historical', city: 'Mardin', location: { type: 'Point', coordinates: [41.4419, 37.3204] }, period: 'Late Antique / Syriac', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Güngören, Midyat/Mardin', images: [], approved: true },

  { name: 'Hasankeyf', description: 'Dicle kıyısındaki Hasankeyf, mağara yerleşimleri ve çok katmanlı tarihî mirasıyla Batman’ın en bilinen kültür alanıdır.', category: 'historical', city: 'Batman', location: { type: 'Point', coordinates: [41.4142, 37.7138] }, period: 'Medieval / Artuqid', entryFee: 0, openingHours: 'Günün her saati', address: 'Hasankeyf/Batman', images: [], approved: true },
  { name: 'Hasankeyf Kalesi', description: 'Dicle Vadisi’ne hâkim kale alanı, Hasankeyf’in savunma ve yerleşim tarihinin merkezindedir.', category: 'castle', city: 'Batman', location: { type: 'Point', coordinates: [41.4160, 37.7147] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Hasankeyf/Batman', images: [], approved: true },
  { name: 'Zeynel Bey Türbesi', description: 'Akkoyunlu dönemine ait türbe, renkli çini süslemeleriyle Hasankeyf mirasının en özel yapılarındandır.', category: 'monument', city: 'Batman', location: { type: 'Point', coordinates: [41.4169, 37.7206] }, period: 'Akkoyunlu', entryFee: 0, openingHours: 'Günün her saati', address: 'Hasankeyf/Batman', images: [], approved: true },
  { name: 'Malabadi Köprüsü', description: 'Batman Çayı üzerindeki köprü, Artuklu dönemi taş köprü mimarisinin en görkemli örneklerinden biridir.', category: 'historical', city: 'Batman', location: { type: 'Point', coordinates: [41.1987, 38.1520] }, period: 'Artuqid', entryFee: 0, openingHours: 'Günün her saati', address: 'Silvan yolu, Batman', images: [], approved: true },

  { name: 'Tillo Kalesi', description: 'Tillo çevresindeki kale alanı, Siirt’in tarihî peyzajı ve manevi merkezleriyle birlikte anılır.', category: 'castle', city: 'Siirt', location: { type: 'Point', coordinates: [42.0107, 37.9491] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Tillo/Siirt', images: [], approved: true },
  { name: 'İsmail Fakirullah Türbesi', description: 'Tillo’daki türbe, ışık hadisesiyle tanınan düzenlemesi ve manevi önemiyle Siirt’in en bilinen ziyaret yerlerindendir.', category: 'monument', city: 'Siirt', location: { type: 'Point', coordinates: [42.0122, 37.9495] }, period: 'Ottoman', entryFee: 0, openingHours: 'Günün her saati', address: 'Tillo/Siirt', images: [], approved: true },
  { name: 'Ulu Camii', description: 'Siirt Ulu Camii, minaresi ve tarihî dokusuyla kent merkezindeki önemli İslam mimarisi örneklerindendir.', category: 'mosque', city: 'Siirt', location: { type: 'Point', coordinates: [41.9446, 37.9291] }, period: 'Seljuk / Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Siirt Merkez', images: [], approved: true },
  { name: 'Veysel Karani Türbesi', description: 'Baykan’daki türbe, bölgenin en önemli dinî ziyaret merkezlerinden biridir.', category: 'monument', city: 'Siirt', location: { type: 'Point', coordinates: [41.7388, 38.1644] }, period: 'Islamic / Modern', entryFee: 0, openingHours: 'Günün her saati', address: 'Baykan/Siirt', images: [], approved: true },

  { name: 'Nemrut Dağı', description: 'Kommagene Krallığı’na ait anıtsal heykeller ve tümülüs, antik dünyanın en etkileyici kutsal alanlarından biridir.', category: 'monument', city: 'Adıyaman', location: { type: 'Point', coordinates: [38.7409, 37.9806] }, period: 'Commagene', entryFee: 0, openingHours: 'Günün her saati', address: 'Kahta/Adıyaman', images: [], approved: true },
  { name: 'Arsameia Antik Kenti', description: 'Kommagene Krallığı’nın yazlık yönetim merkezi olarak bilinen Arsameia, kaya yazıtları ve kabartmalarıyla önem taşır.', category: 'ruins', city: 'Adıyaman', location: { type: 'Point', coordinates: [38.6548, 37.9435] }, period: 'Commagene', entryFee: 0, openingHours: '08:30 - 18:00', address: 'Kahta/Adıyaman', images: [], approved: true },
  { name: 'Cendere Köprüsü', description: 'Roma döneminden kalan köprü, Cendere Çayı üzerinde etkileyici taş mühendisliğiyle günümüze ulaşmıştır.', category: 'historical', city: 'Adıyaman', location: { type: 'Point', coordinates: [38.6082, 37.9328] }, period: 'Roman', entryFee: 0, openingHours: 'Günün her saati', address: 'Kahta/Adıyaman', images: [], approved: true },
  { name: 'Perre Antik Kenti', description: 'Kommagene bölgesinin önemli yerleşimlerinden Perre, kaya mezarları ve nekropol alanıyla tanınır.', category: 'ruins', city: 'Adıyaman', location: { type: 'Point', coordinates: [38.2486, 37.7901] }, period: 'Commagene / Roman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Örenli, Adıyaman', images: [], approved: true },
  { name: 'Karakuş Tümülüsü', description: 'Kommagene kraliyet ailesi kadınları için yapıldığı düşünülen tümülüs, anıtsal sütunlarıyla dikkat çeker.', category: 'monument', city: 'Adıyaman', location: { type: 'Point', coordinates: [38.6137, 37.8692] }, period: 'Commagene', entryFee: 0, openingHours: 'Günün her saati', address: 'Kahta/Adıyaman', images: [], approved: true },

  { name: 'Ravanda Kalesi', description: 'Kilis’in kuzeyinde sarp bir tepe üzerinde yer alan kale, bölgenin Orta Çağ savunma hatlarından biridir.', category: 'castle', city: 'Kilis', location: { type: 'Point', coordinates: [36.9916, 36.8742] }, period: 'Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Polateli/Kilis', images: [], approved: true },
  { name: 'Oylum Höyük', description: 'Kilis yakınındaki höyük, Tunç Çağı’ndan itibaren yerleşim izleri veren önemli bir arkeolojik alandır.', category: 'ruins', city: 'Kilis', location: { type: 'Point', coordinates: [37.1538, 36.7533] }, period: 'Bronze Age', entryFee: 0, openingHours: 'Günün her saati', address: 'Oylum Köyü, Kilis', images: [], approved: true },
  { name: 'Kilis Ulu Camii', description: 'Kilis merkezdeki Ulu Camii, Osmanlı dönemi şehir dokusunun önemli dinî yapılarındandır.', category: 'mosque', city: 'Kilis', location: { type: 'Point', coordinates: [37.1157, 36.7170] }, period: 'Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Kilis Merkez', images: [], approved: true },

  { name: 'Cizre Ulu Camii', description: 'Cizre’nin tarihî merkezindeki cami, bölgenin İslam mimarisi ve kent hafızasında önemli yer tutar.', category: 'mosque', city: 'Şırnak', location: { type: 'Point', coordinates: [42.1902, 37.3300] }, period: 'Islamic / Ottoman', entryFee: 0, openingHours: 'Namaz vakitleri dışında açık', address: 'Cizre/Şırnak', images: [], approved: true },
  { name: 'Nuh Peygamber Türbesi', description: 'Cizre’de yer alan türbe, yerel inanç ve ziyaret geleneğinin en bilinen merkezlerinden biridir.', category: 'monument', city: 'Şırnak', location: { type: 'Point', coordinates: [42.1908, 37.3293] }, period: 'Islamic', entryFee: 0, openingHours: 'Günün her saati', address: 'Cizre/Şırnak', images: [], approved: true },
  { name: 'Finik Ören Yeri', description: 'Dicle Vadisi çevresindeki Finik, kaya kabartmaları ve yerleşim kalıntılarıyla Şırnak’ın arkeolojik mirasını gösterir.', category: 'ruins', city: 'Şırnak', location: { type: 'Point', coordinates: [42.3194, 37.5469] }, period: 'Ancient / Medieval', entryFee: 0, openingHours: 'Günün her saati', address: 'Güçlükonak/Şırnak', images: [], approved: true },
  { name: 'Kırmızı Medrese', description: 'Cizre’deki medrese, kırmızımsı taş dokusu ve tarihî eğitim geleneğiyle kentin önemli yapılarındandır.', category: 'historical', city: 'Şırnak', location: { type: 'Point', coordinates: [42.1905, 37.3297] }, period: 'Islamic / Ottoman', entryFee: 0, openingHours: '09:00 - 17:00', address: 'Cizre/Şırnak', images: [], approved: true },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await City.deleteMany();
    await Place.deleteMany();
    await User.deleteMany();

    // Create admin user
    const admin = await User.create({
      username: 'admin',
      email: 'admin@citylore.com',
      password: 'admin123',
      role: 'admin',
    });
    console.log('✅ Admin user created (email: admin@citylore.com, password: admin123)');

    // Create test user
    await User.create({
      username: 'testuser',
      email: 'test@citylore.com',
      password: 'test123',
    });
    console.log('✅ Test user created (email: test@citylore.com, password: test123)');

    // Seed cities
    const createdCities = await City.insertMany(cities);
    console.log(`✅ ${createdCities.length} cities seeded`);

    // Seed places with city references
    const cityMap = {};
    createdCities.forEach((c) => { cityMap[c.name] = c._id; });

    const placesWithRefs = places.map((p) => ({
      ...p,
      cityId: cityMap[p.city] || null,
      addedBy: admin._id,
    }));

    const createdPlaces = await Place.insertMany(placesWithRefs);
    console.log(`✅ ${createdPlaces.length} places seeded`);

    // Update city place counts
    for (const city of createdCities) {
      const count = createdPlaces.filter((p) => p.city === city.name).length;
      await City.findByIdAndUpdate(city._id, { placeCount: count });
    }
    console.log('✅ City place counts updated');

    console.log('\n🎉 Database seeded successfully!');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
};

seedDB();
