export const LANGUAGE_STORAGE_KEY = 'citylore_language'

const tr = {
  app: { title: "CityLore - Türkiye'nin Tarihi Derinliklerini Keşfet" },
  common: { admin: 'Admin', allTurkey: 'Tüm Türkiye', back: 'Geri', cancel: 'İptal', category: 'Kategori', city: 'Şehir', close: 'Kapat', detailsPage: 'Detay Sayfası', edit: 'Düzenle', email: 'E-posta', free: 'Ücretsiz', loading: 'Yükleniyor...', member: 'Üye', openMap: 'Haritayı Aç', password: 'Şifre', save: 'Kaydet', website: 'Web Sitesi' },
  nav: { addPlace: 'Yer Ekle', connected: 'Canlı', disconnected: 'Bağlantı yok', login: 'Giriş', logout: 'Çıkış', map: 'Harita', profile: 'Profil', register: 'Kayıt' },
  landing: {
    badge: 'Türkiye kültür ve keşif haritası', heroLine1: "Türkiye'yi keşfetmenin", heroLine2: 'en kolay yolu', heroText: 'Tarihi mekanları, şehirleri ve canlı etkinlikleri sade bir interaktif haritada keşfedin; rotanızı planlayın ve yeni durakları kolayca bulun.', explore: 'Keşfet',
    features: [
      { title: 'Tarihi Mekanları Keşfet', text: 'Binlerce yıllık mirasa sahip mekanları detaylı içerikleriyle inceleyin.' },
      { title: 'Canlı Kültürel Etkinlikleri Gör', text: 'Konser, sergi, festival ve daha fazlasını anlık olarak takip edin.' },
      { title: 'Kendi Gezi Rotanı Oluştur', text: 'İlgi alanlarına göre rotalar oluştur, kaydet ve paylaş.' },
    ],
    mapPreview: 'Harita Önizlemesi', mapPreviewTitle: 'Türkiye genelindeki keşif noktaları', openFullMap: 'Tam Haritayı Aç →', density: 'Yoğunluk Düzeyi:', high: 'Yüksek', medium: 'Orta', low: 'Düşük', footerText: "Türkiye'nin kültürel mirasını keşfet, yaşat ve paylaş.", newsletter: 'Bültenimize Katılın', newsletterText: 'Yeni yerler, etkinlikler ve özel içerikler için e-posta listemize katılın.', emailPlaceholder: 'E-posta adresiniz', copyright: '© 2025 CityLore. Tüm hakları saklıdır.',
    footerColumns: [['Keşfet', 'Harita', 'Mekanlar', 'Etkinlikler', 'Rotalar'], ['Hakkımızda', 'Biz Kimiz?', 'Misyonumuz', 'Kariyer', 'İletişim'], ['Destek', 'Yardım Merkezi', 'Kullanım Koşulları', 'Gizlilik Politikası', 'SSS']],
  },
  home: { liveTracking: 'Canlı etkinlik takibi aktif', titlePrefix: "Türkiye'nin", titleHighlight: 'Tarihi Ruhunu', titleSuffix: 'Keşfet', subtitle: 'Binlerce yıllık tarihi mekanlar, anlık kültürel etkinlikler ve sokak sanatı — hepsi tek haritada.', freeRegister: 'Ücretsiz Kayıt', statsCity: 'Şehir', statsPlace: 'Tarihi Mekan', statsLive: 'Canlı Etkinlik', cities: 'Şehirler', viewOnMap: 'Haritada Gör', featured: 'Öne Çıkan Mekanlar', seeAll: 'Tümünü Gör', placeCount: '{count} mekan' },
  auth: { loginTitle: 'Giriş Yap', loginWelcome: "CityLore'a hoş geldiniz", loggingIn: 'Giriş yapılıyor...', noAccount: 'Hesabın yok mu?', registerLink: 'Kayıt ol', registerTitle: 'Kayıt Ol', registerSubtitle: "Türkiye'yi birlikte keşfedelim", username: 'Kullanıcı Adı', passwordMin: 'En az 6 karakter', creating: 'Kayıt oluşturuluyor...', hasAccount: 'Hesabın var mı?', loginLink: 'Giriş yap' },
  profile: { updated: 'Profil güncellendi!', editProfile: 'Profili Düzenle', bio: 'Bio', bioPlaceholder: 'Kendini tanıt...', saving: 'Kaydediliyor...', savedPlaces: 'Kaydedilen Mekanlar', noSaved: 'Henüz kaydedilen mekan yok.', discover: 'Keşfet!', logout: 'Çıkış Yap' },
  admin: { title: 'Admin Paneli', subtitle: 'CityLore yönetim ekranı', totalPlaces: 'Toplam Mekan', liveEvents: 'Canlı Etkinlik', activeUsers: 'Aktif Kullanıcılar', places: 'Mekanlar', events: 'Etkinlikler', placeDeleted: 'Mekan silindi', eventDeleted: 'Etkinlik silindi', place: 'Mekan', rating: 'Puan', noEvents: 'Aktif etkinlik yok' },
  addPlace: { title: 'Yeni Mekan Ekle', subtitle: "Türkiye'nin tarihi zenginliklerine katkıda bulun", basic: 'Temel Bilgiler', name: 'Mekan Adı *', namePlaceholder: 'Ayasofya', description: 'Açıklama *', descriptionPlaceholder: 'Mekan hakkında detaylı bilgi...', period: 'Dönem', location: 'Konum', cityPlaceholder: 'İstanbul', address: 'Adres', addressPlaceholder: 'Sultanahmet, Fatih/İstanbul', latitude: 'Enlem (Lat) *', longitude: 'Boylam (Lng) *', coordsHint: 'OpenStreetMap veya başka bir harita uygulamasında mekanı açıp koordinatları kopyalayabilirsiniz.', details: 'Detaylar', entryFee: 'Giriş Ücreti (₺)', entryFeePlaceholder: '0 = Ücretsiz', openingHours: 'Çalışma Saatleri', imageUrls: "Fotoğraf URL'leri (her satıra bir tane)", streetHelp: 'Optional. Google Maps Embed Street View is used automatically when the frontend has a Google Embed API key. Panoramax or a hosted 360 URL can be added as a fallback.', cameraHelp: 'Optional Google camera settings. Use these when the default panorama opens facing away from the place.', add: '🏛️ Mekanı Ekle', adding: 'Ekleniyor...', added: 'Mekan eklendi!' },
  map: { search: 'Mekan ara...', selectCity: 'Şehir Seç', rainyTitle: 'Yağmurlu Hava Önerisi', rainyText: 'Kapalı mekanları keşfet', places: 'Mekanlar', live: 'Canlı', myRoute: 'Gezi Rotam', emptyRoute: 'Henüz rota oluşturulmadı.', emptyRouteHint: 'Haritadan mekan seçip "Rotaya Ekle" butonuna basarak başlayın.', driving: 'Sürüş', walking: 'Yürüyüş', addToRoute: 'Rotaya Ekle', viewDetails: 'Detayları Görüntüle →', liveEvent: 'Canlı Etkinlik', reportEvent: 'Etkinlik Bildir', eventReported: 'Etkinlik bildirildi! 🎉' },
  place: { notFound: 'Mekan bulunamadı', viewUnavailable: '360 view not available yet', inRoute: 'Rotanızda', reviews: 'Yorumlar', writeReview: 'Yorum Yaz', yourRating: 'Puanın:', reviewPlaceholder: 'Deneyimini paylaş...', sending: 'Gönderiliyor...', sendReview: 'Yorum Gönder', loginToReviewStart: 'Giriş yapın', loginToReviewMiddle: 'veya', registerToReview: 'kayıt olun', loginToReviewEnd: 'yorum yazmak için.', noReviews: 'Henüz yorum yok. İlk yorumu sen yaz!', entryFee: 'Giriş Ücreti', openingHours: 'Çalışma Saatleri', showOnMap: 'Haritada Göster' },
  city: { notFound: 'Şehir bulunamadı', historicalPlaces: '{count} tarihi mekan', empty: 'Bu şehir için henüz mekan eklenmemiş.', addFirst: 'İlk mekanı sen ekle!' },
  eventForm: { title: 'Etkinlik Bildir', eventName: 'Etkinlik Adı *', eventNamePlaceholder: 'Açık hava caz konseri', type: 'Tür *', description: 'Açıklama *', descriptionPlaceholder: 'Etkinlik hakkında kısa bilgi...', addressPlaceholder: 'Taksim Meydanı', latitude: 'Enlem *', longitude: 'Boylam *', coordsHint: 'Şehir merkezi koordinatları otomatik dolduruldu. Düzenleyebilirsiniz.', startTime: 'Başlangıç Zamanı *', reporting: 'Bildiriliyor...', reportLive: 'Canlı Bildir' },
  panorama: { noSource: 'No verified 360 source exists for this place yet.', externalPanorama: 'This backup 360 source opens as an external page and cannot be embedded here. Use the button below to open it.', externalStreet: 'This backup street-level source does not allow embedding. Use the button below to open it.', loading: '360 view loading...', openView: 'Open view', no360: 'No 360 View' },
  chatbot: { welcome: 'Merhaba, ben CityLore Asistanı. Mekanlar, tarih, rotalar, 360 görüntüler veya sıradaki ziyaret noktan hakkında soru sorabilirsin.', error: 'Şu anda chatbot servisine ulaşamadım.', title: 'CityLore Asistanı', subtitle: 'Tarihi mekan rehberi', close: 'Chatbotu kapat', thinking: 'Düşünüyor...', placeholder: 'Mekanlar hakkında sor...', send: 'Mesaj gönder', open: 'Chatbotu aç' },
  toast: { error: 'Hata oluştu', loginFailed: 'Giriş başarısız', welcome: 'Hoş geldin!', passwordMin: 'Şifre en az 6 karakter olmalı', accountCreated: 'Hesabın oluşturuldu!', registerFailed: 'Kayıt başarısız', coordinatesRequired: 'Koordinat girilmeli', coordinatesEnter: 'Koordinat giriniz', saveLogin: 'Kaydetmek için giriş yapın', saved: 'Kaydedildi!', unsaved: 'Kaydedilenlerden çıkarıldı', reviewMin: 'Yorum en az 10 karakter olmalı', reviewAdded: 'Yorumunuz eklendi!', reviewDeleted: 'Yorum silindi', reviewDeleteFailed: 'Yorum silinemedi', alreadyRoute: 'Bu mekan zaten rotanızda!', routeLimit: 'Bir rotaya en fazla 10 mekan ekleyebilirsiniz.', routeAdded: 'Rotaya eklendi! 📍', routeRemoved: 'Rotadan çıkarıldı.', routeCleared: 'Rota temizlendi.' },
  categories: { all: 'Tümü', historical: 'Tarihi', museum: 'Müze', mosque: 'Cami', castle: 'Kale', ruins: 'Harabe', monument: 'Anıt', cultural: 'Kültürel', other: 'Diğer' },
  eventTypes: { concert: '🎵 Konser', flashmob: '💃 Flash Mob', popup: '🛍️ Pop-up Market', exhibition: '🎨 Sergi', festival: '🎉 Festival', protest: '📢 Gösteri', other: '⚡ Diğer' },
}

const en = {
  app: { title: "CityLore - Turkey's Historical Depths" },
  common: { admin: 'Admin', allTurkey: 'All Turkey', back: 'Back', cancel: 'Cancel', category: 'Category', city: 'City', close: 'Close', detailsPage: 'Details Page', edit: 'Edit', email: 'Email', free: 'Free', loading: 'Loading...', member: 'Member', openMap: 'Open Map', password: 'Password', save: 'Save', website: 'Website' },
  nav: { addPlace: 'Add Place', connected: 'Live', disconnected: 'Offline', login: 'Login', logout: 'Logout', map: 'Map', profile: 'Profile', register: 'Sign Up' },
  landing: {
    badge: 'Turkey Culture & Discovery Map', heroLine1: 'The easiest way', heroLine2: 'to discover Turkey', heroText: 'Discover historical places, cities, and live events on one simple interactive map; plan your route and find new stops easily.', explore: 'Explore',
    features: [
      { title: 'Discover Historical Places', text: 'Explore places with thousands of years of heritage through detailed content.' },
      { title: 'See Live Cultural Events', text: 'Follow concerts, exhibitions, festivals, and more in real time.' },
      { title: 'Create Your Own Travel Route', text: 'Build, save, and share routes based on your interests.' },
    ],
    mapPreview: 'Map Preview', mapPreviewTitle: 'Discovery points across Turkey', openFullMap: 'Open Full Map →', density: 'Density Level:', high: 'High', medium: 'Medium', low: 'Low', footerText: "Discover, preserve, and share Turkey's cultural heritage.", newsletter: 'Join Our Newsletter', newsletterText: 'Join our email list for new places, events, and special content.', emailPlaceholder: 'Your email address', copyright: '© 2025 CityLore. All rights reserved.',
    footerColumns: [['Explore', 'Map', 'Places', 'Events', 'Routes'], ['About', 'Who We Are', 'Our Mission', 'Careers', 'Contact'], ['Support', 'Help Center', 'Terms of Use', 'Privacy Policy', 'FAQ']],
  },
  home: { liveTracking: 'Live event tracking active', titlePrefix: 'Discover', titleHighlight: "Turkey's Historical Spirit", titleSuffix: '', subtitle: 'Thousands of years of historical places, real-time cultural events, and street art — all on one map.', freeRegister: 'Free Sign Up', statsCity: 'Cities', statsPlace: 'Historical Places', statsLive: 'Live Events', cities: 'Cities', viewOnMap: 'View on Map', featured: 'Featured Places', seeAll: 'See All', placeCount: '{count} places' },
  auth: { loginTitle: 'Login', loginWelcome: 'Welcome to CityLore', loggingIn: 'Logging in...', noAccount: "Don't have an account?", registerLink: 'Sign up', registerTitle: 'Sign Up', registerSubtitle: "Let's discover Turkey together", username: 'Username', passwordMin: 'At least 6 characters', creating: 'Creating account...', hasAccount: 'Already have an account?', loginLink: 'Log in' },
  profile: { updated: 'Profile updated!', editProfile: 'Edit Profile', bio: 'Bio', bioPlaceholder: 'Introduce yourself...', saving: 'Saving...', savedPlaces: 'Saved Places', noSaved: 'No saved places yet.', discover: 'Explore!', logout: 'Log Out' },
  admin: { title: 'Admin Panel', subtitle: 'CityLore management screen', totalPlaces: 'Total Places', liveEvents: 'Live Events', activeUsers: 'Active Users', places: 'Places', events: 'Events', placeDeleted: 'Place deleted', eventDeleted: 'Event deleted', place: 'Place', rating: 'Rating', noEvents: 'No active events' },
  addPlace: { title: 'Add New Place', subtitle: "Contribute to Turkey's historical richness", basic: 'Basic Information', name: 'Place Name *', namePlaceholder: 'Hagia Sophia', description: 'Description *', descriptionPlaceholder: 'Detailed information about the place...', period: 'Period', location: 'Location', cityPlaceholder: 'Istanbul', address: 'Address', addressPlaceholder: 'Sultanahmet, Fatih/Istanbul', latitude: 'Latitude (Lat) *', longitude: 'Longitude (Lng) *', coordsHint: 'Open the place in OpenStreetMap or another map app and copy its coordinates.', details: 'Details', entryFee: 'Entry Fee (₺)', entryFeePlaceholder: '0 = Free', openingHours: 'Opening Hours', imageUrls: 'Photo URLs (one per line)', streetHelp: 'Optional. Google Maps Embed Street View is used automatically when the frontend has a Google Embed API key. Panoramax or a hosted 360 URL can be added as a fallback.', cameraHelp: 'Optional Google camera settings. Use these when the default panorama opens facing away from the place.', add: '🏛️ Add Place', adding: 'Adding...', added: 'Place added!' },
  map: { search: 'Search places...', selectCity: 'Select City', rainyTitle: 'Rainy Weather Suggestion', rainyText: 'Explore indoor places', places: 'Places', live: 'Live', myRoute: 'My Trip Route', emptyRoute: 'No route created yet.', emptyRouteHint: 'Select a place on the map and press "Add to Route" to begin.', driving: 'Driving', walking: 'Walking', addToRoute: 'Add to Route', viewDetails: 'View Details →', liveEvent: 'Live Event', reportEvent: 'Report Event', eventReported: 'Event reported! 🎉' },
  place: { notFound: 'Place not found', viewUnavailable: '360 view not available yet', inRoute: 'In your route', reviews: 'Reviews', writeReview: 'Write a Review', yourRating: 'Your rating:', reviewPlaceholder: 'Share your experience...', sending: 'Sending...', sendReview: 'Send Review', loginToReviewStart: 'Log in', loginToReviewMiddle: 'or', registerToReview: 'sign up', loginToReviewEnd: 'to write a review.', noReviews: 'No reviews yet. Be the first to write one!', entryFee: 'Entry Fee', openingHours: 'Opening Hours', showOnMap: 'Show on Map' },
  city: { notFound: 'City not found', historicalPlaces: '{count} historical places', empty: 'No places have been added for this city yet.', addFirst: 'Add the first place!' },
  eventForm: { title: 'Report Event', eventName: 'Event Name *', eventNamePlaceholder: 'Open-air jazz concert', type: 'Type *', description: 'Description *', descriptionPlaceholder: 'Short information about the event...', addressPlaceholder: 'Taksim Square', latitude: 'Latitude *', longitude: 'Longitude *', coordsHint: 'City center coordinates were filled automatically. You can edit them.', startTime: 'Start Time *', reporting: 'Reporting...', reportLive: 'Report Live' },
  panorama: { noSource: 'No verified 360 source exists for this place yet.', externalPanorama: 'This backup 360 source opens as an external page and cannot be embedded here. Use the button below to open it.', externalStreet: 'This backup street-level source does not allow embedding. Use the button below to open it.', loading: '360 view loading...', openView: 'Open view', no360: 'No 360 View' },
  chatbot: { welcome: 'Hi, I am CityLore Assistant. Ask me about places, history, routes, 360 views, or what to visit next.', error: 'I could not reach the chatbot service right now.', title: 'CityLore Assistant', subtitle: 'Historical places guide', close: 'Close chatbot', thinking: 'Thinking...', placeholder: 'Ask about places...', send: 'Send message', open: 'Open chatbot' },
  toast: { error: 'An error occurred', loginFailed: 'Login failed', welcome: 'Welcome!', passwordMin: 'Password must be at least 6 characters', accountCreated: 'Your account has been created!', registerFailed: 'Sign up failed', coordinatesRequired: 'Coordinates are required', coordinatesEnter: 'Please enter coordinates', saveLogin: 'Log in to save this place', saved: 'Saved!', unsaved: 'Removed from saved places', reviewMin: 'Review must be at least 10 characters', reviewAdded: 'Your review has been added!', reviewDeleted: 'Review deleted', reviewDeleteFailed: 'Could not delete review', alreadyRoute: 'This place is already in your route!', routeLimit: 'You can add up to 10 places to one route.', routeAdded: 'Added to route! 📍', routeRemoved: 'Removed from route.', routeCleared: 'Route cleared.' },
  categories: { all: 'All', historical: 'Historical', museum: 'Museum', mosque: 'Mosque', castle: 'Castle', ruins: 'Ruins', monument: 'Monument', cultural: 'Cultural', other: 'Other' },
  eventTypes: { concert: '🎵 Concert', flashmob: '💃 Flash Mob', popup: '🛍️ Pop-up Market', exhibition: '🎨 Exhibition', festival: '🎉 Festival', protest: '📢 Demonstration', other: '⚡ Other' },
}

export const translations = { tr, en }

export const entityTranslations = {
  en: {
    Ayasofya: 'Hagia Sophia', 'Topkapı Sarayı': 'Topkapi Palace', 'Efes Antik Kenti': 'Ephesus Ancient City', Kapadokya: 'Cappadocia', Göbeklitepe: 'Gobeklitepe', 'Ani Harabeleri': 'Ani Ruins', 'Sümela Manastırı': 'Sumela Monastery', 'Mevlana Müzesi': 'Mevlana Museum', 'Nemrut Dağı': 'Mount Nemrut',
    'Hevsel Bahçeleri': 'Hevsel Gardens', 'Spil Dağı / Niobe Ağlayan Kaya': 'Mount Spil / Niobe Weeping Rock', 'Spil Dagi / Niobe Aglayan Kaya': 'Mount Spil / Niobe Weeping Rock', 'Ağlayan Kaya': 'Weeping Rock', 'Aglayan Kaya': 'Weeping Rock', 'Spil Dağı': 'Mount Spil', 'Spil Dagi': 'Mount Spil',
    'Vize Antik Tiyatrosu': 'Vize Ancient Theater', 'Justinianus Köprüsü': 'Justinianus Bridge',
    Gelibolu: 'Gallipoli', 'Gelibolu Yarımadası Tarihi Alanı': 'Gallipoli Peninsula Historic Site', 'Gelibolu Yarimadasi Tarihi Alani': 'Gallipoli Peninsula Historic Site', 'Tarihi Alanı': 'Historic Site', 'Tarihi Alani': 'Historic Site', 'Saat Kulesi': 'Clock Tower', 'Yarımadası': 'Peninsula', Yarimadasi: 'Peninsula',
    'Tashan Ve Tasmedrese': 'Tashan and Tasmedrese (Caravanserai & Madrasa)', 'Taşhan ve Taşmedrese': 'Tashan and Tasmedrese (Caravanserai & Madrasa)', Taşhan: 'Caravanserai', Tashan: 'Caravanserai', Han: 'Caravanserai', Medrese: 'Madrasa', Taşmedrese: 'Madrasa', Tasmedrese: 'Madrasa', Bedesten: 'Covered Bazaar', Hamam: 'Turkish Bath', ve: 'and',
    İstanbul: 'Istanbul', İzmir: 'Izmir', Diyarbakır: 'Diyarbakir', Çanakkale: 'Canakkale', Aydın: 'Aydin', Muğla: 'Mugla', Ağrı: 'Agri', Iğdır: 'Igdir', Muş: 'Mus', Bingöl: 'Bingol', Balıkesir: 'Balikesir', Tekirdağ: 'Tekirdag', Kırklareli: 'Kirklareli', Türkiye: 'Turkey',
    Sakarya: 'Sakarya', 'Serdivan/Sakarya': 'Serdivan/Sakarya', 'Vize/Kırklareli': 'Vize/Kirklareli',
    'Tarihin kalbi, iki kıtanın buluşma noktası': 'The heart of history, where two continents meet', 'Cumhuriyetin başkenti': 'The capital of the Republic', "Ege'nin incisi": 'The pearl of the Aegean', "Mevlana'nın şehri": 'The city of Mevlana', "Osmanlı'nın ilk başkenti": 'The first capital of the Ottoman Empire', "Karadeniz'in gözbebeği": 'The jewel of the Black Sea', "Kurtuluş Savaşı'nın başladığı şehir": 'The city where the War of Independence began', "Karadeniz'in en uç noktası": 'The northern tip of the Black Sea coast', 'Peri bacaları ve yeraltı şehirleri': 'Fairy chimneys and underground cities', "Ege'nin ve Akdeniz'in buluştuğu yer": 'Where the Aegean and Mediterranean meet', 'Antik kentler diyarı': 'Land of ancient cities', 'Pamukkale travertenlerinin ev sahibi': 'Home of the Pamukkale travertines',
    'Trakya’daki nadir antik tiyatro örneklerinden biri olan yapı, Vize’nin Roma dönemi kent kimliğini gösterir.': 'One of the rare ancient theater examples in Thrace, this structure reflects Vize’s urban identity during the Roman period.',
    'Trakya’daki nadir antik tiyatro örneklerinden biri olan yapı, Vize’nin Roma dönemi kent kimliğini gösterir': 'One of the rare ancient theater examples in Thrace, this structure reflects Vize’s urban identity during the Roman period',
    'Bizans İmparatoru Justinianus döneminde yaptırılan köprü, Sakarya Nehri çevresinin en önemli antik mühendislik eserlerindendir.': 'Built during the reign of Byzantine Emperor Justinianus, this bridge is one of the most important ancient engineering works around the Sakarya River.',
    'Bizans İmparatoru Justinianus döneminde yaptırılan köprü, Sakarya Nehri çevresinin en önemli antik mühendislik eserlerindendir': 'Built during the reign of Byzantine Emperor Justinianus, this bridge is one of the most important ancient engineering works around the Sakarya River',
    'Cankaya siluetinin simgelerinden olan kule, Ankara manzarasi icin populer bir duraktir.': 'One of the landmarks of the Cankaya skyline, this tower is a popular stop for views of Ankara.',
    'Çankaya siluetinin simgelerinden olan kule, Ankara manzarası için popüler bir duraktır.': 'One of the landmarks of the Cankaya skyline, this tower is a popular stop for views of Ankara.',
    'Volkanik kaya üzerinde yükselen kale, kentin tarihî siluetini belirleyen en güçlü simgedir.': 'Rising on volcanic rock, this castle is the strongest symbol defining the city’s historic skyline.',
    'Volkanik kaya uzerinde yukselen kale, kentin tarihi siluetini belirleyen en guclu simgedir.': 'Rising on volcanic rock, this castle is the strongest symbol defining the city’s historic skyline.',
    'Günün her saati': 'Open all day', 'Namaz vakitleri dışında açık': 'Open outside prayer times', Tarihi: 'Historical', Müze: 'Museum', Cami: 'Mosque', Camii: 'Mosque', Kale: 'Castle', Harabe: 'Ruins', Anıt: 'Monument', Kültürel: 'Cultural', Diğer: 'Other', Tiyatro: 'Theater', Fener: 'Lighthouse', Köprü: 'Bridge', Saray: 'Palace', Kilise: 'Church', 'İç Anadolu': 'Central Anatolia', 'Doğu Anadolu': 'Eastern Anatolia', 'Güneydoğu Anadolu': 'Southeastern Anatolia', Karadeniz: 'Black Sea', Akdeniz: 'Mediterranean',
    Bizans: 'Byzantine', Roma: 'Roman', 'Antik Tiyatro': 'Ancient Theater', Köprü: 'Bridge',
  },
}
